/*
 * xHarbour build 1.1.0 Intl. (SimpLex)
 * Generated C source code from <DEMO_FWH.prg>
 * Command: C:\xhb804\bin\harbour.exe C:\Sistemas Fivewin\Fast Report\DEMO_FWH.prg /q /oC:\Sistemas Fivewin\Fast Report\DEMO_FWH.c /M /N 
 * Created: 2014.02.20 08:25:34 (Borland C++ 5.5.1 (32 bit))
 */

#include "hbvmpub.h"
#include "hbpcode.h"
#include "hbinit.h"

#define __PRG_SOURCE__ "DEMO_FWH.prg"

HB_FUNC( MAIN );
HB_FUNC( GENERATEITEMS );
HB_FUNC( UNLOADFR );
HB_FUNC( DOFRACTION );
HB_FUNC( DOSIMPLELIST );
HB_FUNC( DOSIMPLEGROUP );
HB_FUNC( DOMORECOMPLEX );
HB_FUNC( DOINFR_MORECOMPLEX );
HB_FUNC( MYMANUALREPORT );
HB_FUNC( DOMANUALREPORT );
HB_FUNC( DOMEMPICT );
HB_FUNC( DOUSERDS );
HB_FUNC( GETDSVALUE );
HB_FUNC( DOWAUSERDS );
HB_FUNC( DOADO );
HB_FUNC( DOSOMECALLS );
HB_FUNC( GETEXPORTOBJECT );
HB_FUNC( ONEXPRELEASE );
HB_FUNC( CALLUSERFUNCTION );
HB_FUNC( ALLFILESEXIST );
HB_FUNC( SHOWPROGRESS );
HB_FUNC( SHOWPROCESS );


/* Skipped DEFERRED call to: 'DIVERTCONSTRUCTORCALL' */
HB_FUNC_EXTERN( GETPROCADDRESS );
HB_FUNC_EXTERN( TACTIVEX );
HB_FUNC_EXTERN( ERRORSYS );
HB_FUNC_EXTERN( __MVPRIVATE );
HB_FUNC_EXTERN( DBFCDX );
HB_FUNC_EXTERN( TFONT );
HB_FUNC_EXTERN( CURDRIVE );
HB_FUNC_EXTERN( CURDIR );
HB_FUNC_EXTERN( SET );
HB_FUNC_EXTERN( DBUSEAREA );
HB_FUNC_EXTERN( DBCREATEINDEX );
HB_FUNC_EXTERN( DBCLOSEAREA );
HB_FUNC_EXTERN( STR );
HB_FUNC_EXTERN( ORDLISTCLEAR );
HB_FUNC_EXTERN( ORDLISTADD );
HB_FUNC_EXTERN( ORDSETFOCUS );
HB_FUNC_EXTERN( DBGOTOP );
HB_FUNC_EXTERN( TDIALOG );
HB_FUNC_EXTERN( SPACE );
HB_FUNC_EXTERN( TRADMENU );
HB_FUNC_EXTERN( PCOUNT );
HB_FUNC_EXTERN( TCOMBOBOX );
HB_FUNC_EXTERN( ALLTRIM );
HB_FUNC_EXTERN( TBUTTON );
HB_FUNC_EXTERN( TSAY );
HB_FUNC_EXTERN( FRREPORTMANAGER );
HB_FUNC_EXTERN( DIRECTORY );
HB_FUNC_EXTERN( LEN );
HB_FUNC_EXTERN( AADD );
HB_FUNC_EXTERN( SUBSTR );
HB_FUNC_EXTERN( ASCAN );
HB_FUNC_EXTERN( MSGALERT );
HB_FUNC_EXTERN( DBSELECTAREA );
HB_FUNC_EXTERN( DBSETRELATION );
HB_FUNC_EXTERN( DBCLEARRELATION );
HB_FUNC_EXTERN( ORDSCOPE );
HB_FUNC_EXTERN( DBEVAL );
HB_FUNC_EXTERN( DBSKIP );
HB_FUNC_EXTERN( EOF );
HB_FUNC_EXTERN( CTOD );
HB_FUNC_EXTERN( ARRAY );
HB_FUNC_EXTERN( TWBROWSE );
HB_FUNC_EXTERN( TGET );
HB_FUNC_EXTERN( TCHECKBOX );
HB_FUNC_EXTERN( FILE );
HB_FUNC_EXTERN( TRIM );

#undef HB_PRG_PCODE_VER
#define HB_PRG_PCODE_VER 9

#include "hbapi.h"


HB_INIT_SYMBOLS_BEGIN( hb_vm_SymbolInit_DEMO_FWH )
{ "DIVERTCONSTRUCTORCALL", {HB_FS_PUBLIC | HB_FS_DEFERRED}, {NULL}, NULL },
{ "GETPROCADDRESS", {HB_FS_PUBLIC}, {HB_FUNCNAME( GETPROCADDRESS )}, NULL },
{ "TACTIVEX", {HB_FS_PUBLIC}, {HB_FUNCNAME( TACTIVEX )}, NULL },
{ "ERRORSYS", {HB_FS_PUBLIC}, {HB_FUNCNAME( ERRORSYS )}, NULL },
{ "MAIN", {HB_FS_PUBLIC | HB_FS_LOCAL | HB_FS_FIRST}, {HB_FUNCNAME( MAIN )}, &ModuleFakeDyn },
{ "FRPRN", {HB_FS_PUBLIC}, {NULL}, NULL },
{ "LSHOWCUSTNAME", {HB_FS_PUBLIC}, {NULL}, NULL },
{ "NACTION", {HB_FS_PUBLIC}, {NULL}, NULL },
{ "__MVPRIVATE", {HB_FS_PUBLIC}, {HB_FUNCNAME( __MVPRIVATE )}, NULL },
{ "DBFCDX", {HB_FS_PUBLIC}, {HB_FUNCNAME( DBFCDX )}, NULL },
{ "NEW", {HB_FS_PUBLIC}, {NULL}, NULL },
{ "TFONT", {HB_FS_PUBLIC}, {HB_FUNCNAME( TFONT )}, NULL },
{ "CURDRIVE", {HB_FS_PUBLIC}, {HB_FUNCNAME( CURDRIVE )}, NULL },
{ "CURDIR", {HB_FS_PUBLIC}, {HB_FUNCNAME( CURDIR )}, NULL },
{ "REPDIR", {HB_FS_PUBLIC}, {NULL}, NULL },
{ "DATADIR", {HB_FS_PUBLIC}, {NULL}, NULL },
{ "RESDIR", {HB_FS_PUBLIC}, {NULL}, NULL },
{ "SET", {HB_FS_PUBLIC}, {HB_FUNCNAME( SET )}, NULL },
{ "ALLFILESEXIST", {HB_FS_PUBLIC | HB_FS_LOCAL}, {HB_FUNCNAME( ALLFILESEXIST )}, &ModuleFakeDyn },
{ "DBUSEAREA", {HB_FS_PUBLIC}, {HB_FUNCNAME( DBUSEAREA )}, NULL },
{ "DBCREATEINDEX", {HB_FS_PUBLIC}, {HB_FUNCNAME( DBCREATEINDEX )}, NULL },
{ "CUSTNO", {HB_FS_PUBLIC}, {NULL}, NULL },
{ "COMPANY", {HB_FS_PUBLIC}, {NULL}, NULL },
{ "DBCLOSEAREA", {HB_FS_PUBLIC}, {HB_FUNCNAME( DBCLOSEAREA )}, NULL },
{ "ORDERNO", {HB_FS_PUBLIC}, {NULL}, NULL },
{ "STR", {HB_FS_PUBLIC}, {HB_FUNCNAME( STR )}, NULL },
{ "ITEMNO", {HB_FS_PUBLIC}, {NULL}, NULL },
{ "PARTNO", {HB_FS_PUBLIC}, {NULL}, NULL },
{ "ORDLISTCLEAR", {HB_FS_PUBLIC}, {HB_FUNCNAME( ORDLISTCLEAR )}, NULL },
{ "ORDLISTADD", {HB_FS_PUBLIC}, {HB_FUNCNAME( ORDLISTADD )}, NULL },
{ "ORDSETFOCUS", {HB_FS_PUBLIC}, {HB_FUNCNAME( ORDSETFOCUS )}, NULL },
{ "DBGOTOP", {HB_FS_PUBLIC}, {HB_FUNCNAME( DBGOTOP )}, NULL },
{ "TDIALOG", {HB_FS_PUBLIC}, {HB_FUNCNAME( TDIALOG )}, NULL },
{ "_LHELPICON", {HB_FS_PUBLIC}, {NULL}, NULL },
{ "CCOMBO", {HB_FS_PUBLIC}, {NULL}, NULL },
{ "SPACE", {HB_FS_PUBLIC}, {HB_FUNCNAME( SPACE )}, NULL },
{ "CNOME", {HB_FS_PUBLIC}, {NULL}, NULL },
{ "CDESC", {HB_FS_PUBLIC}, {NULL}, NULL },
{ "CSTAT1", {HB_FS_PUBLIC}, {NULL}, NULL },
{ "CSTAT2", {HB_FS_PUBLIC}, {NULL}, NULL },
{ "REDEFINE", {HB_FS_PUBLIC}, {NULL}, NULL },
{ "TRADMENU", {HB_FS_PUBLIC}, {HB_FUNCNAME( TRADMENU )}, NULL },
{ "PCOUNT", {HB_FS_PUBLIC}, {HB_FUNCNAME( PCOUNT )}, NULL },
{ "OGET1", {HB_FS_PUBLIC}, {NULL}, NULL },
{ "TCOMBOBOX", {HB_FS_PUBLIC}, {HB_FUNCNAME( TCOMBOBOX )}, NULL },
{ "LOADLANGRES", {HB_FS_PUBLIC}, {NULL}, NULL },
{ "ALLTRIM", {HB_FS_PUBLIC}, {HB_FUNCNAME( ALLTRIM )}, NULL },
{ "OCOMBO", {HB_FS_PUBLIC}, {NULL}, NULL },
{ "TBUTTON", {HB_FS_PUBLIC}, {HB_FUNCNAME( TBUTTON )}, NULL },
{ "DOSIMPLELIST", {HB_FS_PUBLIC | HB_FS_LOCAL}, {HB_FUNCNAME( DOSIMPLELIST )}, &ModuleFakeDyn },
{ "DOSIMPLEGROUP", {HB_FS_PUBLIC | HB_FS_LOCAL}, {HB_FUNCNAME( DOSIMPLEGROUP )}, &ModuleFakeDyn },
{ "DOMORECOMPLEX", {HB_FS_PUBLIC | HB_FS_LOCAL}, {HB_FUNCNAME( DOMORECOMPLEX )}, &ModuleFakeDyn },
{ "DOUSERDS", {HB_FS_PUBLIC | HB_FS_LOCAL}, {HB_FUNCNAME( DOUSERDS )}, &ModuleFakeDyn },
{ "DOWAUSERDS", {HB_FS_PUBLIC | HB_FS_LOCAL}, {HB_FUNCNAME( DOWAUSERDS )}, &ModuleFakeDyn },
{ "DOADO", {HB_FS_PUBLIC | HB_FS_LOCAL}, {HB_FUNCNAME( DOADO )}, &ModuleFakeDyn },
{ "DOSOMECALLS", {HB_FS_PUBLIC | HB_FS_LOCAL}, {HB_FUNCNAME( DOSOMECALLS )}, &ModuleFakeDyn },
{ "DOINFR_MORECOMPLEX", {HB_FS_PUBLIC | HB_FS_LOCAL}, {HB_FUNCNAME( DOINFR_MORECOMPLEX )}, &ModuleFakeDyn },
{ "DOMEMPICT", {HB_FS_PUBLIC | HB_FS_LOCAL}, {HB_FUNCNAME( DOMEMPICT )}, &ModuleFakeDyn },
{ "DOMANUALREPORT", {HB_FS_PUBLIC | HB_FS_LOCAL}, {HB_FUNCNAME( DOMANUALREPORT )}, &ModuleFakeDyn },
{ "END", {HB_FS_PUBLIC}, {NULL}, NULL },
{ "TSAY", {HB_FS_PUBLIC}, {HB_FUNCNAME( TSAY )}, NULL },
{ "ONOME", {HB_FS_PUBLIC}, {NULL}, NULL },
{ "MEMO", {HB_FS_PUBLIC}, {NULL}, NULL },
{ "ODESC", {HB_FS_PUBLIC}, {NULL}, NULL },
{ "OSTAT1", {HB_FS_PUBLIC}, {NULL}, NULL },
{ "OSTAT2", {HB_FS_PUBLIC}, {NULL}, NULL },
{ "FRREPORTMANAGER", {HB_FS_PUBLIC}, {HB_FUNCNAME( FRREPORTMANAGER )}, NULL },
{ "SETICON", {HB_FS_PUBLIC}, {NULL}, NULL },
{ "SETTITLE", {HB_FS_PUBLIC}, {NULL}, NULL },
{ "SETEVENTHANDLER", {HB_FS_PUBLIC}, {NULL}, NULL },
{ "SHOWPROGRESS", {HB_FS_PUBLIC | HB_FS_LOCAL}, {HB_FUNCNAME( SHOWPROGRESS )}, &ModuleFakeDyn },
{ "SHOWPROCESS", {HB_FS_PUBLIC | HB_FS_LOCAL}, {HB_FUNCNAME( SHOWPROCESS )}, &ModuleFakeDyn },
{ "CALLUSERFUNCTION", {HB_FS_PUBLIC | HB_FS_LOCAL}, {HB_FUNCNAME( CALLUSERFUNCTION )}, &ModuleFakeDyn },
{ "ADDFUNCTION", {HB_FS_PUBLIC}, {NULL}, NULL },
{ "ACTIVATE", {HB_FS_PUBLIC}, {NULL}, NULL },
{ "BLCLICKED", {HB_FS_PUBLIC}, {NULL}, NULL },
{ "BMOVED", {HB_FS_PUBLIC}, {NULL}, NULL },
{ "BPAINTED", {HB_FS_PUBLIC}, {NULL}, NULL },
{ "GENERATEITEMS", {HB_FS_PUBLIC | HB_FS_LOCAL}, {HB_FUNCNAME( GENERATEITEMS )}, &ModuleFakeDyn },
{ "BRCLICKED", {HB_FS_PUBLIC}, {NULL}, NULL },
{ "UNLOADFR", {HB_FS_PUBLIC | HB_FS_LOCAL}, {HB_FUNCNAME( UNLOADFR )}, &ModuleFakeDyn },
{ "DIRECTORY", {HB_FS_PUBLIC}, {HB_FUNCNAME( DIRECTORY )}, NULL },
{ "ATMP", {HB_FS_PUBLIC}, {NULL}, NULL },
{ "X", {HB_FS_PUBLIC}, {NULL}, NULL },
{ "LEN", {HB_FS_PUBLIC}, {HB_FUNCNAME( LEN )}, NULL },
{ "AADD", {HB_FS_PUBLIC}, {HB_FUNCNAME( AADD )}, NULL },
{ "SUBSTR", {HB_FS_PUBLIC}, {HB_FUNCNAME( SUBSTR )}, NULL },
{ "SETITEMS", {HB_FS_PUBLIC}, {NULL}, NULL },
{ "SET", {HB_FS_PUBLIC}, {NULL}, NULL },
{ "DESTROYFR", {HB_FS_PUBLIC}, {NULL}, NULL },
{ "DOFRACTION", {HB_FS_PUBLIC | HB_FS_LOCAL}, {HB_FUNCNAME( DOFRACTION )}, &ModuleFakeDyn },
{ "CEXPOBJ", {HB_FS_PUBLIC}, {NULL}, NULL },
{ "CEXPFILE", {HB_FS_PUBLIC}, {NULL}, NULL },
{ "LEXPOPT", {HB_FS_PUBLIC}, {NULL}, NULL },
{ "LEXPOPEN", {HB_FS_PUBLIC}, {NULL}, NULL },
{ "CEXTENTION", {HB_FS_PUBLIC}, {NULL}, NULL },
{ "LOADFROMFILE", {HB_FS_PUBLIC}, {NULL}, NULL },
{ "SETNAME", {HB_FS_PUBLIC}, {NULL}, NULL },
{ "REPORTOPTIONS", {HB_FS_PUBLIC}, {NULL}, NULL },
{ "SETDESCRIPTION", {HB_FS_PUBLIC}, {NULL}, NULL },
{ "REFRESH", {HB_FS_PUBLIC}, {NULL}, NULL },
{ "SHOWREPORT", {HB_FS_PUBLIC}, {NULL}, NULL },
{ "DESIGNREPORT", {HB_FS_PUBLIC}, {NULL}, NULL },
{ "SETPROPERTY", {HB_FS_PUBLIC}, {NULL}, NULL },
{ "PREPAREREPORT", {HB_FS_PUBLIC}, {NULL}, NULL },
{ "PRINT", {HB_FS_PUBLIC}, {NULL}, NULL },
{ "GETEXPORTOBJECT", {HB_FS_PUBLIC | HB_FS_LOCAL}, {HB_FUNCNAME( GETEXPORTOBJECT )}, &ModuleFakeDyn },
{ "ASCAN", {HB_FS_PUBLIC}, {HB_FUNCNAME( ASCAN )}, NULL },
{ "DOEXPORT", {HB_FS_PUBLIC}, {NULL}, NULL },
{ "MSGALERT", {HB_FS_PUBLIC}, {HB_FUNCNAME( MSGALERT )}, NULL },
{ "_CNOOPEN", {HB_FS_PUBLIC}, {NULL}, NULL },
{ "SETWORKAREA", {HB_FS_PUBLIC}, {NULL}, NULL },
{ "SETFIELDALIASES", {HB_FS_PUBLIC}, {NULL}, NULL },
{ "CLEARDATASETS", {HB_FS_PUBLIC}, {NULL}, NULL },
{ "DBSELECTAREA", {HB_FS_PUBLIC}, {HB_FUNCNAME( DBSELECTAREA )}, NULL },
{ "SETMASTERDETAIL", {HB_FS_PUBLIC}, {NULL}, NULL },
{ "CUSTOMER", {HB_FS_PUBLIC}, {NULL}, NULL },
{ "ORDERS", {HB_FS_PUBLIC}, {NULL}, NULL },
{ "DBSETRELATION", {HB_FS_PUBLIC}, {HB_FUNCNAME( DBSETRELATION )}, NULL },
{ "SETRESYNCPAIR", {HB_FS_PUBLIC}, {NULL}, NULL },
{ "DBCLEARRELATION", {HB_FS_PUBLIC}, {HB_FUNCNAME( DBCLEARRELATION )}, NULL },
{ "MYMANUALREPORT", {HB_FS_PUBLIC | HB_FS_LOCAL}, {HB_FUNCNAME( MYMANUALREPORT )}, &ModuleFakeDyn },
{ "SETDEFAULTFONTPROPERTY", {HB_FS_PUBLIC}, {NULL}, NULL },
{ "MEMOAT", {HB_FS_PUBLIC}, {NULL}, NULL },
{ "TMP_NAME", {HB_FS_PUBLIC}, {NULL}, NULL },
{ "SETMANUALOBJPROPERTY", {HB_FS_PUBLIC}, {NULL}, NULL },
{ "LINEAT", {HB_FS_PUBLIC}, {NULL}, NULL },
{ "PICTUREAT", {HB_FS_PUBLIC}, {NULL}, NULL },
{ "NEWPAGE", {HB_FS_PUBLIC}, {NULL}, NULL },
{ "STARTMANUALBUILD", {HB_FS_PUBLIC}, {NULL}, NULL },
{ "BIOLIFE", {HB_FS_PUBLIC}, {NULL}, NULL },
{ "ADIR", {HB_FS_PUBLIC}, {NULL}, NULL },
{ "I", {HB_FS_PUBLIC}, {NULL}, NULL },
{ "DIRNAME", {HB_FS_PUBLIC}, {NULL}, NULL },
{ "SETUSERDATASET", {HB_FS_PUBLIC}, {NULL}, NULL },
{ "XX", {HB_FS_PUBLIC}, {NULL}, NULL },
{ "GETDSVALUE", {HB_FS_PUBLIC | HB_FS_LOCAL}, {HB_FUNCNAME( GETDSVALUE )}, &ModuleFakeDyn },
{ "PARTS", {HB_FS_PUBLIC}, {NULL}, NULL },
{ "DESCRIPTIO", {HB_FS_PUBLIC}, {NULL}, NULL },
{ "ORDSCOPE", {HB_FS_PUBLIC}, {HB_FUNCNAME( ORDSCOPE )}, NULL },
{ "DBEVAL", {HB_FS_PUBLIC}, {HB_FUNCNAME( DBEVAL )}, NULL },
{ "QTY", {HB_FS_PUBLIC}, {NULL}, NULL },
{ "LISTPRICE", {HB_FS_PUBLIC}, {NULL}, NULL },
{ "DBSKIP", {HB_FS_PUBLIC}, {HB_FUNCNAME( DBSKIP )}, NULL },
{ "EOF", {HB_FS_PUBLIC}, {HB_FUNCNAME( EOF )}, NULL },
{ "SETADOCONNECTPARTSTR", {HB_FS_PUBLIC}, {NULL}, NULL },
{ "ADDVARIABLE", {HB_FS_PUBLIC}, {NULL}, NULL },
{ "CTOD", {HB_FS_PUBLIC}, {HB_FUNCNAME( CTOD )}, NULL },
{ "ARRAY", {HB_FS_PUBLIC}, {HB_FUNCNAME( ARRAY )}, NULL },
{ "TWBROWSE", {HB_FS_PUBLIC}, {HB_FUNCNAME( TWBROWSE )}, NULL },
{ "NAT", {HB_FS_PUBLIC}, {NULL}, NULL },
{ "SETARRAY", {HB_FS_PUBLIC}, {NULL}, NULL },
{ "TGET", {HB_FS_PUBLIC}, {HB_FUNCNAME( TGET )}, NULL },
{ "TCHECKBOX", {HB_FS_PUBLIC}, {HB_FUNCNAME( TCHECKBOX )}, NULL },
{ "ONEXPRELEASE", {HB_FS_PUBLIC | HB_FS_LOCAL}, {HB_FUNCNAME( ONEXPRELEASE )}, &ModuleFakeDyn },
{ "FILE", {HB_FS_PUBLIC}, {HB_FUNCNAME( FILE )}, NULL },
{ "TRIM", {HB_FS_PUBLIC}, {HB_FUNCNAME( TRIM )}, NULL }
HB_INIT_SYMBOLS_END( hb_vm_SymbolInit_DEMO_FWH )

#if defined(HB_PRAGMA_STARTUP)
   #pragma startup hb_vm_SymbolInit_DEMO_FWH
#elif defined(HB_MSC_STARTUP)
   #if _MSC_VER >= 1010
      #pragma data_seg( ".CRT$XIY" )
      #pragma comment( linker, "/Merge:.CRT=.data" )
   #else
      #pragma data_seg( "XIY" )
   #endif
   static HB_$INITSYM hb_vm_auto_SymbolInit_DEMO_FWH = hb_vm_SymbolInit_DEMO_FWH;
   #pragma data_seg()
#endif

HB_FUNC( MAIN )
{
   static const BYTE pcode[] =
   {
	HB_P_FRAME, 5, 0,	/* locals, params */
/* 00003 */ HB_P_BASELINE, 22, 0,	/* 22 */
	HB_P_LOCALNEARSETSTR, 5, 12, 0,	/* _CTITLE 12*/
	'F', 'a', 's', 't', ' ', 'R', 'e', 'p', 'o', 'r', 't', 0, 
/* 00022 */ HB_P_LINEOFFSET, 5,	/* 27 */
	HB_P_FALSE,
	HB_P_ONE,
	HB_P_PUSHSYMNEAR, 8,	/* __MVPRIVATE */
	HB_P_PUSHNIL,
	HB_P_PUSHSYMNEAR, 5,	/* FRPRN */
	HB_P_PUSHSYMNEAR, 6,	/* LSHOWCUSTNAME */
	HB_P_PUSHSYMNEAR, 7,	/* NACTION */
	HB_P_DOSHORT, 3,
	HB_P_POPVARIABLE, 7, 0,	/* NACTION */
	HB_P_POPMEMVAR, 6, 0,	/* LSHOWCUSTNAME */
/* 00043 */ HB_P_LINEOFFSET, 8,	/* 30 */
	HB_P_MESSAGE, 10, 0,	/* NEW */
	HB_P_PUSHSYMNEAR, 11,	/* TFONT */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_PUSHSTRSHORT, 14,	/* 14 */
	'M', 'S', ' ', 'S', 'a', 'n', 's', ' ', 'S', 'e', 'r', 'i', 'f', 0, 
	HB_P_ZERO,
	HB_P_PUSHBYTE, 248,	/* -8 */
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_TRUE,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_SENDSHORT, 17,
	HB_P_POPLOCALNEAR, 4,	/* OFONT */
/* 00090 */ HB_P_LINEOFFSET, 10,	/* 32 */
	HB_P_PUSHSYMNEAR, 12,	/* CURDRIVE */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_PUSHSTRSHORT, 3,	/* 3 */
	':', 92, 0, 
	HB_P_PLUS,
	HB_P_PUSHSYMNEAR, 13,	/* CURDIR */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_PLUS,
	HB_P_PUSHSTRSHORT, 7,	/* 7 */
	92, 'R', 'E', 'P', 'S', 92, 0, 
	HB_P_PLUS,
	HB_P_POPMEMVAR, 14, 0,	/* REPDIR */
/* 00122 */ HB_P_LINEOFFSET, 11,	/* 33 */
	HB_P_PUSHSYMNEAR, 12,	/* CURDRIVE */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_PUSHSTRSHORT, 3,	/* 3 */
	':', 92, 0, 
	HB_P_PLUS,
	HB_P_PUSHSYMNEAR, 13,	/* CURDIR */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_PLUS,
	HB_P_PUSHSTRSHORT, 7,	/* 7 */
	92, 'D', 'A', 'T', 'A', 92, 0, 
	HB_P_PLUS,
	HB_P_POPMEMVAR, 15, 0,	/* DATADIR */
/* 00154 */ HB_P_LINEOFFSET, 12,	/* 34 */
	HB_P_PUSHSYMNEAR, 12,	/* CURDRIVE */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_PUSHSTRSHORT, 3,	/* 3 */
	':', 92, 0, 
	HB_P_PLUS,
	HB_P_PUSHSYMNEAR, 13,	/* CURDIR */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_PLUS,
	HB_P_PUSHSTRSHORT, 10,	/* 10 */
	92, 'L', 'A', 'N', 'G', 'R', 'E', 'S', 92, 0, 
	HB_P_PLUS,
	HB_P_POPMEMVAR, 16, 0,	/* RESDIR */
/* 00189 */ HB_P_LINEOFFSET, 14,	/* 36 */
	HB_P_PUSHSYMNEAR, 17,	/* SET */
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 7,	/* 7 */
	HB_P_PUSHSTRSHORT, 6,	/* 6 */
	'd', 'a', 't', 'a', 92, 0, 
	HB_P_DOSHORT, 2,
/* 00206 */ HB_P_LINEOFFSET, 16,	/* 38 */
	HB_P_PUSHSYMNEAR, 18,	/* ALLFILESEXIST */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 10,	/* 10 */
	'C', 'U', 'S', 'T', 'A', '.', 'N', 'T', 'X', 0, 
	HB_P_PUSHSTRSHORT, 10,	/* 10 */
	'C', 'U', 'S', 'T', 'B', '.', 'N', 'T', 'X', 0, 
	HB_P_ARRAYGEN, 2, 0,	/* 2 */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_JUMPTRUENEAR, 97,	/* 97 (abs: 00337) */
/* 00242 */ HB_P_LINEOFFSET, 17,	/* 39 */
	HB_P_PUSHSYMNEAR, 19,	/* DBUSEAREA */
	HB_P_PUSHNIL,
	HB_P_FALSE,
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 9,	/* 9 */
	'C', 'u', 's', 't', 'o', 'm', 'e', 'r', 0, 
	HB_P_PUSHNIL,
	HB_P_FALSE,
	HB_P_FALSE,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 8,
/* 00267 */ HB_P_LINEOFFSET, 18,	/* 40 */
	HB_P_PUSHSYMNEAR, 20,	/* DBCREATEINDEX */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 6,	/* 6 */
	'C', 'u', 's', 't', 'A', 0, 
	HB_P_PUSHSTRSHORT, 7,	/* 7 */
	'C', 'u', 's', 't', 'N', 'o', 0, 
	HB_P_PUSHBLOCKSHORT, 6,	/* 6 */
	HB_P_PUSHFIELD, 21, 0,	/* CUSTNO */
	HB_P_ENDBLOCK,
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 4,
/* 00298 */ HB_P_LINEOFFSET, 19,	/* 41 */
	HB_P_PUSHSYMNEAR, 20,	/* DBCREATEINDEX */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 6,	/* 6 */
	'C', 'u', 's', 't', 'B', 0, 
	HB_P_PUSHSTRSHORT, 8,	/* 8 */
	'C', 'o', 'm', 'p', 'a', 'n', 'y', 0, 
	HB_P_PUSHBLOCKSHORT, 6,	/* 6 */
	HB_P_PUSHFIELD, 22, 0,	/* COMPANY */
	HB_P_ENDBLOCK,
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 4,
/* 00330 */ HB_P_LINEOFFSET, 20,	/* 42 */
	HB_P_PUSHSYMNEAR, 23,	/* DBCLOSEAREA */
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 0,
/* 00337 */ HB_P_LINEOFFSET, 23,	/* 45 */
	HB_P_PUSHSYMNEAR, 18,	/* ALLFILESEXIST */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 12,	/* 12 */
	'O', 'R', 'D', 'E', 'R', 'S', 'A', '.', 'N', 'T', 'X', 0, 
	HB_P_PUSHSTRSHORT, 12,	/* 12 */
	'O', 'R', 'D', 'E', 'R', 'S', 'B', '.', 'N', 'T', 'X', 0, 
	HB_P_ARRAYGEN, 2, 0,	/* 2 */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_JUMPTRUENEAR, 99,	/* 99 (abs: 00474) */
/* 00377 */ HB_P_LINEOFFSET, 24,	/* 46 */
	HB_P_PUSHSYMNEAR, 19,	/* DBUSEAREA */
	HB_P_PUSHNIL,
	HB_P_FALSE,
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 7,	/* 7 */
	'O', 'r', 'd', 'e', 'r', 's', 0, 
	HB_P_PUSHNIL,
	HB_P_FALSE,
	HB_P_FALSE,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 8,
/* 00400 */ HB_P_LINEOFFSET, 25,	/* 47 */
	HB_P_PUSHSYMNEAR, 20,	/* DBCREATEINDEX */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 8,	/* 8 */
	'O', 'R', 'D', 'E', 'R', 'S', 'A', 0, 
	HB_P_PUSHSTRSHORT, 8,	/* 8 */
	'O', 'r', 'd', 'e', 'r', 'N', 'o', 0, 
	HB_P_PUSHBLOCKSHORT, 6,	/* 6 */
	HB_P_PUSHFIELD, 24, 0,	/* ORDERNO */
	HB_P_ENDBLOCK,
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 4,
/* 00434 */ HB_P_LINEOFFSET, 26,	/* 48 */
	HB_P_PUSHSYMNEAR, 20,	/* DBCREATEINDEX */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 8,	/* 8 */
	'O', 'R', 'D', 'E', 'R', 'S', 'B', 0, 
	HB_P_PUSHSTRSHORT, 7,	/* 7 */
	'C', 'u', 's', 't', 'N', 'o', 0, 
	HB_P_PUSHBLOCKSHORT, 6,	/* 6 */
	HB_P_PUSHFIELD, 21, 0,	/* CUSTNO */
	HB_P_ENDBLOCK,
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 4,
/* 00467 */ HB_P_LINEOFFSET, 27,	/* 49 */
	HB_P_PUSHSYMNEAR, 23,	/* DBCLOSEAREA */
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 0,
/* 00474 */ HB_P_LINEOFFSET, 30,	/* 52 */
	HB_P_PUSHSYMNEAR, 18,	/* ALLFILESEXIST */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 11,	/* 11 */
	'i', 't', 'e', 'm', 's', 'a', '.', 'N', 'T', 'X', 0, 
	HB_P_PUSHSTRSHORT, 11,	/* 11 */
	'i', 't', 'e', 'm', 's', 'b', '.', 'N', 'T', 'X', 0, 
	HB_P_PUSHSTRSHORT, 11,	/* 11 */
	'i', 't', 'e', 'm', 's', 'c', '.', 'N', 'T', 'X', 0, 
	HB_P_ARRAYGEN, 3, 0,	/* 3 */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_JUMPTRUE, 173, 0,	/* 173 (abs: 00696) */
/* 00526 */ HB_P_LINEOFFSET, 31,	/* 53 */
	HB_P_PUSHSYMNEAR, 19,	/* DBUSEAREA */
	HB_P_PUSHNIL,
	HB_P_FALSE,
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 6,	/* 6 */
	'I', 't', 'e', 'm', 's', 0, 
	HB_P_PUSHNIL,
	HB_P_FALSE,
	HB_P_FALSE,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 8,
/* 00548 */ HB_P_LINEOFFSET, 32,	/* 54 */
	HB_P_PUSHSYMNEAR, 20,	/* DBCREATEINDEX */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 7,	/* 7 */
	'i', 't', 'e', 'm', 's', 'a', 0, 
	HB_P_PUSHSTRSHORT, 33,	/* 33 */
	's', 't', 'r', '(', 'O', 'r', 'd', 'e', 'r', 'N', 'o', ',', ' ', '1', '5', ')', '+', 's', 't', 'r', '(', 'I', 't', 'e', 'm', 'N', 'o', ',', ' ', '1', '5', ')', 0, 
	HB_P_PUSHBLOCKSHORT, 24,	/* 24 */
	HB_P_PUSHSYMNEAR, 25,	/* STR */
	HB_P_PUSHNIL,
	HB_P_PUSHFIELD, 24, 0,	/* ORDERNO */
	HB_P_PUSHBYTE, 15,	/* 15 */
	HB_P_FUNCTIONSHORT, 2,
	HB_P_PUSHSYMNEAR, 25,	/* STR */
	HB_P_PUSHNIL,
	HB_P_PUSHFIELD, 26, 0,	/* ITEMNO */
	HB_P_PUSHBYTE, 15,	/* 15 */
	HB_P_FUNCTIONSHORT, 2,
	HB_P_PLUS,
	HB_P_ENDBLOCK,
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 4,
/* 00624 */ HB_P_LINEOFFSET, 33,	/* 55 */
	HB_P_PUSHSYMNEAR, 20,	/* DBCREATEINDEX */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 7,	/* 7 */
	'i', 't', 'e', 'm', 's', 'b', 0, 
	HB_P_PUSHSTRSHORT, 8,	/* 8 */
	'O', 'r', 'd', 'e', 'r', 'N', 'o', 0, 
	HB_P_PUSHBLOCKSHORT, 6,	/* 6 */
	HB_P_PUSHFIELD, 24, 0,	/* ORDERNO */
	HB_P_ENDBLOCK,
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 4,
/* 00657 */ HB_P_LINEOFFSET, 34,	/* 56 */
	HB_P_PUSHSYMNEAR, 20,	/* DBCREATEINDEX */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 7,	/* 7 */
	'i', 't', 'e', 'm', 's', 'c', 0, 
	HB_P_PUSHSTRSHORT, 7,	/* 7 */
	'P', 'a', 'r', 't', 'N', 'o', 0, 
	HB_P_PUSHBLOCKSHORT, 6,	/* 6 */
	HB_P_PUSHFIELD, 27, 0,	/* PARTNO */
	HB_P_ENDBLOCK,
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 4,
/* 00689 */ HB_P_LINEOFFSET, 35,	/* 57 */
	HB_P_PUSHSYMNEAR, 23,	/* DBCLOSEAREA */
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 0,
/* 00696 */ HB_P_LINEOFFSET, 38,	/* 60 */
	HB_P_PUSHSYMNEAR, 18,	/* ALLFILESEXIST */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 10,	/* 10 */
	'p', 'a', 'r', 't', 's', '.', 'N', 'T', 'X', 0, 
	HB_P_PUSHNIL,
	HB_P_ARRAYGEN, 2, 0,	/* 2 */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_JUMPTRUENEAR, 62,	/* 62 (abs: 00781) */
/* 00721 */ HB_P_LINEOFFSET, 39,	/* 61 */
	HB_P_PUSHSYMNEAR, 19,	/* DBUSEAREA */
	HB_P_PUSHNIL,
	HB_P_FALSE,
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 6,	/* 6 */
	'P', 'a', 'r', 't', 's', 0, 
	HB_P_PUSHNIL,
	HB_P_FALSE,
	HB_P_FALSE,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 8,
/* 00743 */ HB_P_LINEOFFSET, 40,	/* 62 */
	HB_P_PUSHSYMNEAR, 20,	/* DBCREATEINDEX */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 6,	/* 6 */
	'p', 'a', 'r', 't', 's', 0, 
	HB_P_PUSHSTRSHORT, 7,	/* 7 */
	'P', 'a', 'r', 't', 'N', 'o', 0, 
	HB_P_PUSHBLOCKSHORT, 6,	/* 6 */
	HB_P_PUSHFIELD, 27, 0,	/* PARTNO */
	HB_P_ENDBLOCK,
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 4,
/* 00774 */ HB_P_LINEOFFSET, 41,	/* 63 */
	HB_P_PUSHSYMNEAR, 23,	/* DBCLOSEAREA */
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 0,
/* 00781 */ HB_P_LINEOFFSET, 45,	/* 67 */
	HB_P_PUSHSYMNEAR, 17,	/* SET */
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 11,	/* 11 */
	HB_P_PUSHSTRSHORT, 3,	/* 3 */
	'O', 'N', 0, 
	HB_P_DOSHORT, 2,
/* 00795 */ HB_P_LINEOFFSET, 47,	/* 69 */
	HB_P_PUSHSYMNEAR, 19,	/* DBUSEAREA */
	HB_P_PUSHNIL,
	HB_P_TRUE,
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 9,	/* 9 */
	'C', 'u', 's', 't', 'o', 'm', 'e', 'r', 0, 
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_FALSE,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 8,
/* 00820 */ HB_P_LINEOFFSET, 48,	/* 70 */
	HB_P_PUSHSYMNEAR, 28,	/* ORDLISTCLEAR */
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 0,
	HB_P_PUSHSYMNEAR, 29,	/* ORDLISTADD */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 6,	/* 6 */
	'C', 'u', 's', 't', 'A', 0, 
	HB_P_DOSHORT, 1,
	HB_P_PUSHSYMNEAR, 29,	/* ORDLISTADD */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 6,	/* 6 */
	'C', 'u', 's', 't', 'B', 0, 
	HB_P_DOSHORT, 1,
/* 00853 */ HB_P_LINEOFFSET, 49,	/* 71 */
	HB_P_PUSHSYMNEAR, 30,	/* ORDSETFOCUS */
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 2,	/* 2 */
	HB_P_DOSHORT, 1,
/* 00862 */ HB_P_LINEOFFSET, 50,	/* 72 */
	HB_P_PUSHSYMNEAR, 31,	/* DBGOTOP */
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 0,
/* 00869 */ HB_P_LINEOFFSET, 52,	/* 74 */
	HB_P_PUSHSYMNEAR, 19,	/* DBUSEAREA */
	HB_P_PUSHNIL,
	HB_P_TRUE,
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 7,	/* 7 */
	'O', 'r', 'd', 'e', 'r', 's', 0, 
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_FALSE,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 8,
/* 00892 */ HB_P_LINEOFFSET, 53,	/* 75 */
	HB_P_PUSHSYMNEAR, 28,	/* ORDLISTCLEAR */
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 0,
	HB_P_PUSHSYMNEAR, 29,	/* ORDLISTADD */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 8,	/* 8 */
	'O', 'R', 'D', 'E', 'R', 'S', 'A', 0, 
	HB_P_DOSHORT, 1,
	HB_P_PUSHSYMNEAR, 29,	/* ORDLISTADD */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 8,	/* 8 */
	'O', 'R', 'D', 'E', 'R', 'S', 'B', 0, 
	HB_P_DOSHORT, 1,
/* 00929 */ HB_P_LINEOFFSET, 54,	/* 76 */
	HB_P_PUSHSYMNEAR, 30,	/* ORDSETFOCUS */
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 2,	/* 2 */
	HB_P_DOSHORT, 1,
/* 00938 */ HB_P_LINEOFFSET, 55,	/* 77 */
	HB_P_PUSHSYMNEAR, 31,	/* DBGOTOP */
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 0,
/* 00945 */ HB_P_LINEOFFSET, 57,	/* 79 */
	HB_P_PUSHSYMNEAR, 19,	/* DBUSEAREA */
	HB_P_PUSHNIL,
	HB_P_TRUE,
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 6,	/* 6 */
	'I', 't', 'e', 'm', 's', 0, 
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_FALSE,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 8,
/* 00967 */ HB_P_LINEOFFSET, 58,	/* 80 */
	HB_P_PUSHSYMNEAR, 28,	/* ORDLISTCLEAR */
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 0,
	HB_P_PUSHSYMNEAR, 29,	/* ORDLISTADD */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 7,	/* 7 */
	'i', 't', 'e', 'm', 's', 'a', 0, 
	HB_P_DOSHORT, 1,
	HB_P_PUSHSYMNEAR, 29,	/* ORDLISTADD */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 7,	/* 7 */
	'i', 't', 'e', 'm', 's', 'b', 0, 
	HB_P_DOSHORT, 1,
	HB_P_PUSHSYMNEAR, 29,	/* ORDLISTADD */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 7,	/* 7 */
	'i', 't', 'e', 'm', 's', 'c', 0, 
	HB_P_DOSHORT, 1,
/* 01016 */ HB_P_LINEOFFSET, 59,	/* 81 */
	HB_P_PUSHSYMNEAR, 30,	/* ORDSETFOCUS */
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 2,	/* 2 */
	HB_P_DOSHORT, 1,
/* 01025 */ HB_P_LINEOFFSET, 60,	/* 82 */
	HB_P_PUSHSYMNEAR, 31,	/* DBGOTOP */
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 0,
/* 01032 */ HB_P_LINEOFFSET, 62,	/* 84 */
	HB_P_PUSHSYMNEAR, 19,	/* DBUSEAREA */
	HB_P_PUSHNIL,
	HB_P_TRUE,
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 6,	/* 6 */
	'P', 'a', 'r', 't', 's', 0, 
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_FALSE,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 8,
/* 01054 */ HB_P_LINEOFFSET, 63,	/* 85 */
	HB_P_PUSHSYMNEAR, 28,	/* ORDLISTCLEAR */
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 0,
	HB_P_PUSHSYMNEAR, 29,	/* ORDLISTADD */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 6,	/* 6 */
	'P', 'a', 'r', 't', 's', 0, 
	HB_P_DOSHORT, 1,
/* 01074 */ HB_P_LINEOFFSET, 64,	/* 86 */
	HB_P_PUSHSYMNEAR, 30,	/* ORDSETFOCUS */
	HB_P_PUSHNIL,
	HB_P_ONE,
	HB_P_DOSHORT, 1,
/* 01082 */ HB_P_LINEOFFSET, 65,	/* 87 */
	HB_P_PUSHSYMNEAR, 31,	/* DBGOTOP */
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 0,
/* 01089 */ HB_P_LINEOFFSET, 67,	/* 89 */
	HB_P_MESSAGE, 10, 0,	/* NEW */
	HB_P_PUSHSYMNEAR, 32,	/* TDIALOG */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 5,	/* 5 */
	'D', 'E', 'M', 'O', 0, 
	HB_P_PUSHNIL,
	HB_P_FALSE,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_FALSE,
	HB_P_PUSHSTRSHORT, 5,	/* 5 */
	'D', 'E', 'M', 'O', 0, 
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_FALSE,
	HB_P_SENDSHORT, 20,
	HB_P_POPLOCALNEAR, 3,	/* ODLG */
/* 01135 */ HB_P_LINEOFFSET, 68,	/* 90 */
	HB_P_MESSAGE, 33, 0,	/* _LHELPICON */
	HB_P_PUSHLOCALNEAR, 3,	/* ODLG */
	HB_P_FALSE,
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 01146 */ HB_P_LINEOFFSET, 70,	/* 92 */
	HB_P_PUSHSTRSHORT, 8,	/* 8 */
	'E', 'n', 'g', 'l', 'i', 's', 'h', 0, 
	HB_P_POPVARIABLE, 34, 0,	/* CCOMBO */
	HB_P_PUSHSYMNEAR, 35,	/* SPACE */
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 50,	/* 50 */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_POPVARIABLE, 36, 0,	/* CNOME */
	HB_P_PUSHSYMNEAR, 35,	/* SPACE */
	HB_P_PUSHNIL,
	HB_P_PUSHINT, 44, 1,	/* 300 */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_POPVARIABLE, 37, 0,	/* CDESC */
	HB_P_PUSHSTRSHORT, 10,	/* 10 */
	'N', 'o', ' ', 'r', 'e', 'p', 'o', 'r', 't', 0, 
	HB_P_POPVARIABLE, 38, 0,	/* CSTAT1 */
	HB_P_PUSHSYMNEAR, 35,	/* SPACE */
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 50,	/* 50 */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_POPVARIABLE, 39, 0,	/* CSTAT2 */
/* 01207 */ HB_P_LINEOFFSET, 72,	/* 94 */
	HB_P_MESSAGE, 40, 0,	/* REDEFINE */
	HB_P_PUSHSYMNEAR, 41,	/* TRADMENU */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_PUSHBLOCK, 28, 0,	/* 28 */
	1, 0,	/* number of local parameters (1) */
	0, 0,	/* number of local variables (0) */
	HB_P_PUSHSYMNEAR, 42,	/* PCOUNT */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_ZERO,
	HB_P_EXACTLYEQUAL,
	HB_P_JUMPFALSENEAR, 7,	/* 7 (abs: 01238) */
	HB_P_PUSHVARIABLE, 7, 0,	/* NACTION */
	HB_P_JUMPNEAR, 8,	/* 8 (abs: 01244) */
	HB_P_PUSHLOCALNEAR, 1,	/* codeblockvar1 */
	HB_P_DUPLICATE,
	HB_P_POPVARIABLE, 7, 0,	/* NACTION */
	HB_P_ENDBLOCK,
	HB_P_PUSHLOCALNEAR, 3,	/* ODLG */
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 101,	/* 101 */
	HB_P_PUSHBYTE, 102,	/* 102 */
	HB_P_PUSHBYTE, 103,	/* 103 */
	HB_P_PUSHBYTE, 104,	/* 104 */
	HB_P_ARRAYGEN, 4, 0,	/* 4 */
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_TRUE,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_SENDSHORT, 11,
	HB_P_POPVARIABLE, 43, 0,	/* OGET1 */
/* 01271 */ HB_P_LINEOFFSET, 76,	/* 98 */
	HB_P_MESSAGE, 40, 0,	/* REDEFINE */
	HB_P_PUSHSYMNEAR, 44,	/* TCOMBOBOX */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_PUSHBYTE, 105,	/* 105 */
	HB_P_PUSHBLOCK, 28, 0,	/* 28 */
	1, 0,	/* number of local parameters (1) */
	0, 0,	/* number of local variables (0) */
	HB_P_PUSHSYMNEAR, 42,	/* PCOUNT */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_ZERO,
	HB_P_EXACTLYEQUAL,
	HB_P_JUMPFALSENEAR, 7,	/* 7 (abs: 01304) */
	HB_P_PUSHVARIABLE, 34, 0,	/* CCOMBO */
	HB_P_JUMPNEAR, 8,	/* 8 (abs: 01310) */
	HB_P_PUSHLOCALNEAR, 1,	/* codeblockvar1 */
	HB_P_DUPLICATE,
	HB_P_POPVARIABLE, 34, 0,	/* CCOMBO */
	HB_P_ENDBLOCK,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHBLOCK, 36, 0,	/* 36 */
	1, 0,	/* number of local parameters (1) */
	0, 0,	/* number of local variables (0) */
	HB_P_MESSAGE, 45, 0,	/* LOADLANGRES */
	HB_P_PUSHMEMVAR, 5, 0,	/* FRPRN */
	HB_P_PUSHMEMVAR, 16, 0,	/* RESDIR */
	HB_P_PUSHSYMNEAR, 46,	/* ALLTRIM */
	HB_P_PUSHNIL,
	HB_P_PUSHVARIABLE, 34, 0,	/* CCOMBO */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_PLUS,
	HB_P_PUSHSTRSHORT, 5,	/* 5 */
	'.', 'x', 'm', 'l', 0, 
	HB_P_PLUS,
	HB_P_SENDSHORT, 1,
	HB_P_ENDBLOCK,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_TRUE,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_SENDSHORT, 17,
	HB_P_POPVARIABLE, 47, 0,	/* OCOMBO */
/* 01366 */ HB_P_LINEOFFSET, 77,	/* 99 */
	HB_P_MESSAGE, 40, 0,	/* REDEFINE */
	HB_P_PUSHSYMNEAR, 48,	/* TBUTTON */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_PUSHINT, 245, 1,	/* 501 */
	HB_P_PUSHBLOCKSHORT, 8,	/* 8 */
	HB_P_PUSHSYMNEAR, 49,	/* DOSIMPLELIST */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_ENDBLOCK,
	HB_P_PUSHLOCALNEAR, 3,	/* ODLG */
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_TRUE,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_FALSE,
	HB_P_SENDSHORT, 10,
	HB_P_POP,
/* 01399 */ HB_P_LINEOFFSET, 78,	/* 100 */
	HB_P_MESSAGE, 40, 0,	/* REDEFINE */
	HB_P_PUSHSYMNEAR, 48,	/* TBUTTON */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_PUSHINT, 246, 1,	/* 502 */
	HB_P_PUSHBLOCKSHORT, 8,	/* 8 */
	HB_P_PUSHSYMNEAR, 50,	/* DOSIMPLEGROUP */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_ENDBLOCK,
	HB_P_PUSHLOCALNEAR, 3,	/* ODLG */
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_TRUE,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_FALSE,
	HB_P_SENDSHORT, 10,
	HB_P_POP,
/* 01432 */ HB_P_LINEOFFSET, 79,	/* 101 */
	HB_P_MESSAGE, 40, 0,	/* REDEFINE */
	HB_P_PUSHSYMNEAR, 48,	/* TBUTTON */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_PUSHINT, 247, 1,	/* 503 */
	HB_P_PUSHBLOCKSHORT, 8,	/* 8 */
	HB_P_PUSHSYMNEAR, 51,	/* DOMORECOMPLEX */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_ENDBLOCK,
	HB_P_PUSHLOCALNEAR, 3,	/* ODLG */
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_TRUE,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_FALSE,
	HB_P_SENDSHORT, 10,
	HB_P_POP,
/* 01465 */ HB_P_LINEOFFSET, 80,	/* 102 */
	HB_P_MESSAGE, 40, 0,	/* REDEFINE */
	HB_P_PUSHSYMNEAR, 48,	/* TBUTTON */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_PUSHINT, 248, 1,	/* 504 */
	HB_P_PUSHBLOCKSHORT, 8,	/* 8 */
	HB_P_PUSHSYMNEAR, 52,	/* DOUSERDS */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_ENDBLOCK,
	HB_P_PUSHLOCALNEAR, 3,	/* ODLG */
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_TRUE,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_FALSE,
	HB_P_SENDSHORT, 10,
	HB_P_POP,
/* 01498 */ HB_P_LINEOFFSET, 81,	/* 103 */
	HB_P_MESSAGE, 40, 0,	/* REDEFINE */
	HB_P_PUSHSYMNEAR, 48,	/* TBUTTON */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_PUSHINT, 249, 1,	/* 505 */
	HB_P_PUSHBLOCKSHORT, 8,	/* 8 */
	HB_P_PUSHSYMNEAR, 53,	/* DOWAUSERDS */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_ENDBLOCK,
	HB_P_PUSHLOCALNEAR, 3,	/* ODLG */
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_TRUE,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_FALSE,
	HB_P_SENDSHORT, 10,
	HB_P_POP,
/* 01531 */ HB_P_LINEOFFSET, 82,	/* 104 */
	HB_P_MESSAGE, 40, 0,	/* REDEFINE */
	HB_P_PUSHSYMNEAR, 48,	/* TBUTTON */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_PUSHINT, 250, 1,	/* 506 */
	HB_P_PUSHBLOCKSHORT, 8,	/* 8 */
	HB_P_PUSHSYMNEAR, 54,	/* DOADO */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_ENDBLOCK,
	HB_P_PUSHLOCALNEAR, 3,	/* ODLG */
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_TRUE,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_FALSE,
	HB_P_SENDSHORT, 10,
	HB_P_POP,
/* 01564 */ HB_P_LINEOFFSET, 83,	/* 105 */
	HB_P_MESSAGE, 40, 0,	/* REDEFINE */
	HB_P_PUSHSYMNEAR, 48,	/* TBUTTON */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_PUSHINT, 251, 1,	/* 507 */
	HB_P_PUSHBLOCKSHORT, 8,	/* 8 */
	HB_P_PUSHSYMNEAR, 55,	/* DOSOMECALLS */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_ENDBLOCK,
	HB_P_PUSHLOCALNEAR, 3,	/* ODLG */
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_TRUE,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_FALSE,
	HB_P_SENDSHORT, 10,
	HB_P_POP,
/* 01597 */ HB_P_LINEOFFSET, 84,	/* 106 */
	HB_P_MESSAGE, 40, 0,	/* REDEFINE */
	HB_P_PUSHSYMNEAR, 48,	/* TBUTTON */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_PUSHINT, 252, 1,	/* 508 */
	HB_P_PUSHBLOCKSHORT, 8,	/* 8 */
	HB_P_PUSHSYMNEAR, 56,	/* DOINFR_MORECOMPLEX */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_ENDBLOCK,
	HB_P_PUSHLOCALNEAR, 3,	/* ODLG */
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_TRUE,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_FALSE,
	HB_P_SENDSHORT, 10,
	HB_P_POP,
/* 01630 */ HB_P_LINEOFFSET, 85,	/* 107 */
	HB_P_MESSAGE, 40, 0,	/* REDEFINE */
	HB_P_PUSHSYMNEAR, 48,	/* TBUTTON */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_PUSHINT, 253, 1,	/* 509 */
	HB_P_PUSHBLOCKSHORT, 8,	/* 8 */
	HB_P_PUSHSYMNEAR, 57,	/* DOMEMPICT */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_ENDBLOCK,
	HB_P_PUSHLOCALNEAR, 3,	/* ODLG */
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_TRUE,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_FALSE,
	HB_P_SENDSHORT, 10,
	HB_P_POP,
/* 01663 */ HB_P_LINEOFFSET, 86,	/* 108 */
	HB_P_MESSAGE, 40, 0,	/* REDEFINE */
	HB_P_PUSHSYMNEAR, 48,	/* TBUTTON */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_PUSHINT, 254, 1,	/* 510 */
	HB_P_PUSHBLOCKSHORT, 8,	/* 8 */
	HB_P_PUSHSYMNEAR, 58,	/* DOMANUALREPORT */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_ENDBLOCK,
	HB_P_PUSHLOCALNEAR, 3,	/* ODLG */
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_TRUE,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_FALSE,
	HB_P_SENDSHORT, 10,
	HB_P_POP,
/* 01696 */ HB_P_LINEOFFSET, 87,	/* 109 */
	HB_P_MESSAGE, 40, 0,	/* REDEFINE */
	HB_P_PUSHSYMNEAR, 48,	/* TBUTTON */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_PUSHINT, 38, 2,	/* 550 */
	HB_P_PUSHBLOCK, 17, 0,	/* 17 */
	0, 0,	/* number of local parameters (0) */
	1, 0,	/* number of local variables (1) */
	3, 0,	/* ODLG */
	HB_P_MESSAGE, 59, 0,	/* END */
	HB_P_PUSHLOCALNEAR, 255,	/* localvar1 */
	HB_P_SENDSHORT, 0,
	HB_P_ENDBLOCK,
	HB_P_PUSHLOCALNEAR, 3,	/* ODLG */
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_TRUE,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_FALSE,
	HB_P_SENDSHORT, 10,
	HB_P_POP,
/* 01738 */ HB_P_LINEOFFSET, 88,	/* 110 */
	HB_P_MESSAGE, 40, 0,	/* REDEFINE */
	HB_P_PUSHSYMNEAR, 60,	/* TSAY */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_PUSHBYTE, 108,	/* 108 */
	HB_P_PUSHBLOCKSHORT, 6,	/* 6 */
	HB_P_PUSHVARIABLE, 36, 0,	/* CNOME */
	HB_P_ENDBLOCK,
	HB_P_PUSHLOCALNEAR, 3,	/* ODLG */
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_TRUE,
	HB_P_PUSHNIL,
	HB_P_SENDSHORT, 8,
	HB_P_POPVARIABLE, 61, 0,	/* ONOME */
/* 01768 */ HB_P_LINEOFFSET, 89,	/* 111 */
	HB_P_MESSAGE, 40, 0,	/* REDEFINE */
	HB_P_PUSHSYMNEAR, 60,	/* TSAY */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_PUSHBYTE, 109,	/* 109 */
	HB_P_PUSHBLOCKSHORT, 6,	/* 6 */
	HB_P_PUSHVARIABLE, 37, 0,	/* CDESC */
	HB_P_ENDBLOCK,
	HB_P_PUSHLOCALNEAR, 3,	/* ODLG */
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_TRUE,
	HB_P_PUSHNIL,
	HB_P_SENDSHORT, 8,
	HB_P_DUPLICATE,
	HB_P_POPVARIABLE, 62, 0,	/* MEMO */
	HB_P_POPVARIABLE, 63, 0,	/* ODESC */
/* 01802 */ HB_P_LINEOFFSET, 90,	/* 112 */
	HB_P_MESSAGE, 40, 0,	/* REDEFINE */
	HB_P_PUSHSYMNEAR, 60,	/* TSAY */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_PUSHBYTE, 110,	/* 110 */
	HB_P_PUSHBLOCKSHORT, 6,	/* 6 */
	HB_P_PUSHVARIABLE, 38, 0,	/* CSTAT1 */
	HB_P_ENDBLOCK,
	HB_P_PUSHLOCALNEAR, 3,	/* ODLG */
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_TRUE,
	HB_P_PUSHNIL,
	HB_P_SENDSHORT, 8,
	HB_P_POPVARIABLE, 64, 0,	/* OSTAT1 */
/* 01832 */ HB_P_LINEOFFSET, 91,	/* 113 */
	HB_P_MESSAGE, 40, 0,	/* REDEFINE */
	HB_P_PUSHSYMNEAR, 60,	/* TSAY */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_PUSHBYTE, 112,	/* 112 */
	HB_P_PUSHBLOCKSHORT, 6,	/* 6 */
	HB_P_PUSHVARIABLE, 39, 0,	/* CSTAT2 */
	HB_P_ENDBLOCK,
	HB_P_PUSHLOCALNEAR, 3,	/* ODLG */
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_TRUE,
	HB_P_PUSHNIL,
	HB_P_SENDSHORT, 8,
	HB_P_POPVARIABLE, 65, 0,	/* OSTAT2 */
/* 01862 */ HB_P_LINEOFFSET, 99,	/* 121 */
	HB_P_MESSAGE, 10, 0,	/* NEW */
	HB_P_PUSHSYMNEAR, 66,	/* FRREPORTMANAGER */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_SENDSHORT, 0,
	HB_P_POPMEMVAR, 5, 0,	/* FRPRN */
/* 01877 */ HB_P_LINEOFFSET, 103,	/* 125 */
	HB_P_MESSAGE, 67, 0,	/* SETICON */
	HB_P_PUSHMEMVAR, 5, 0,	/* FRPRN */
	HB_P_PUSHBYTE, 2,	/* 2 */
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 01890 */ HB_P_LINEOFFSET, 107,	/* 129 */
	HB_P_MESSAGE, 68, 0,	/* SETTITLE */
	HB_P_PUSHMEMVAR, 5, 0,	/* FRPRN */
	HB_P_PUSHLOCALNEAR, 5,	/* _CTITLE */
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 01903 */ HB_P_LINEOFFSET, 116,	/* 138 */
	HB_P_MESSAGE, 69, 0,	/* SETEVENTHANDLER */
	HB_P_PUSHMEMVAR, 5, 0,	/* FRPRN */
	HB_P_PUSHSTRSHORT, 7,	/* 7 */
	'R', 'e', 'p', 'o', 'r', 't', 0, 
	HB_P_PUSHSTRSHORT, 16,	/* 16 */
	'O', 'n', 'P', 'r', 'o', 'g', 'r', 'e', 's', 's', 'S', 't', 'a', 'r', 't', 0, 
	HB_P_PUSHBLOCK, 18, 0,	/* 18 */
	2, 0,	/* number of local parameters (2) */
	0, 0,	/* number of local variables (0) */
	HB_P_PUSHSYMNEAR, 70,	/* SHOWPROGRESS */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 1,	/* codeblockvar1 */
	HB_P_PUSHLOCALNEAR, 2,	/* codeblockvar2 */
	HB_P_ONE,
	HB_P_FUNCTIONSHORT, 3,
	HB_P_ENDBLOCK,
	HB_P_SENDSHORT, 3,
	HB_P_POP,
/* 01959 */ HB_P_LINEOFFSET, 117,	/* 139 */
	HB_P_MESSAGE, 69, 0,	/* SETEVENTHANDLER */
	HB_P_PUSHMEMVAR, 5, 0,	/* FRPRN */
	HB_P_PUSHSTRSHORT, 7,	/* 7 */
	'R', 'e', 'p', 'o', 'r', 't', 0, 
	HB_P_PUSHSTRSHORT, 15,	/* 15 */
	'O', 'n', 'P', 'r', 'o', 'g', 'r', 'e', 's', 's', 'S', 't', 'o', 'p', 0, 
	HB_P_PUSHBLOCK, 19, 0,	/* 19 */
	2, 0,	/* number of local parameters (2) */
	0, 0,	/* number of local variables (0) */
	HB_P_PUSHSYMNEAR, 70,	/* SHOWPROGRESS */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 1,	/* codeblockvar1 */
	HB_P_PUSHLOCALNEAR, 2,	/* codeblockvar2 */
	HB_P_PUSHBYTE, 2,	/* 2 */
	HB_P_FUNCTIONSHORT, 3,
	HB_P_ENDBLOCK,
	HB_P_SENDSHORT, 3,
	HB_P_POP,
/* 02015 */ HB_P_LINEOFFSET, 118,	/* 140 */
	HB_P_MESSAGE, 69, 0,	/* SETEVENTHANDLER */
	HB_P_PUSHMEMVAR, 5, 0,	/* FRPRN */
	HB_P_PUSHSTRSHORT, 7,	/* 7 */
	'R', 'e', 'p', 'o', 'r', 't', 0, 
	HB_P_PUSHSTRSHORT, 11,	/* 11 */
	'O', 'n', 'P', 'r', 'o', 'g', 'r', 'e', 's', 's', 0, 
	HB_P_PUSHBLOCK, 19, 0,	/* 19 */
	2, 0,	/* number of local parameters (2) */
	0, 0,	/* number of local variables (0) */
	HB_P_PUSHSYMNEAR, 70,	/* SHOWPROGRESS */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 1,	/* codeblockvar1 */
	HB_P_PUSHLOCALNEAR, 2,	/* codeblockvar2 */
	HB_P_PUSHBYTE, 3,	/* 3 */
	HB_P_FUNCTIONSHORT, 3,
	HB_P_ENDBLOCK,
	HB_P_SENDSHORT, 3,
	HB_P_POP,
/* 02067 */ HB_P_LINEOFFSET, 119,	/* 141 */
	HB_P_MESSAGE, 69, 0,	/* SETEVENTHANDLER */
	HB_P_PUSHMEMVAR, 5, 0,	/* FRPRN */
	HB_P_PUSHSTRSHORT, 7,	/* 7 */
	'R', 'e', 'p', 'o', 'r', 't', 0, 
	HB_P_PUSHSTRSHORT, 14,	/* 14 */
	'O', 'n', 'B', 'e', 'f', 'o', 'r', 'e', 'P', 'r', 'i', 'n', 't', 0, 
	HB_P_PUSHBLOCK, 15, 0,	/* 15 */
	1, 0,	/* number of local parameters (1) */
	0, 0,	/* number of local variables (0) */
	HB_P_PUSHSYMNEAR, 71,	/* SHOWPROCESS */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 1,	/* codeblockvar1 */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_ENDBLOCK,
	HB_P_SENDSHORT, 3,
	HB_P_POP,
/* 02118 */ HB_P_LINEOFFSET, 123,	/* 145 */
	HB_P_MESSAGE, 69, 0,	/* SETEVENTHANDLER */
	HB_P_PUSHMEMVAR, 5, 0,	/* FRPRN */
	HB_P_PUSHSTRSHORT, 7,	/* 7 */
	'R', 'e', 'p', 'o', 'r', 't', 0, 
	HB_P_PUSHSTRSHORT, 15,	/* 15 */
	'O', 'n', 'U', 's', 'e', 'r', 'F', 'u', 'n', 'c', 't', 'i', 'o', 'n', 0, 
	HB_P_PUSHBLOCK, 17, 0,	/* 17 */
	2, 0,	/* number of local parameters (2) */
	0, 0,	/* number of local variables (0) */
	HB_P_PUSHSYMNEAR, 72,	/* CALLUSERFUNCTION */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 1,	/* codeblockvar1 */
	HB_P_PUSHLOCALNEAR, 2,	/* codeblockvar2 */
	HB_P_FUNCTIONSHORT, 2,
	HB_P_ENDBLOCK,
	HB_P_SENDSHORT, 3,
	HB_P_POP,
/* 02172 */ HB_P_LINEOFFSET, 125,	/* 147 */
	HB_P_MESSAGE, 73, 0,	/* ADDFUNCTION */
	HB_P_PUSHMEMVAR, 5, 0,	/* FRPRN */
	HB_P_PUSHSTRSHORT, 103,	/* 103 */
	'f', 'u', 'n', 'c', 't', 'i', 'o', 'n', ' ', 'X', 'B', 'a', 's', 'e', 'S', 't', 'r', '(', 'n', 'V', 'a', 'l', 'u', 'e', ':', ' ', 'D', 'o', 'u', 'b', 'l', 'e', ',', ' ', 'n', 'L', 'e', 'n', 'g', 't', 'h', ':', ' ', 'V', 'a', 'r', 'i', 'a', 'n', 't', ' ', '=', ' ', 'E', 'm', 'p', 't', 'y', 'V', 'a', 'r', ',', ' ', 'n', 'D', 'e', 'c', 'i', 'm', 'a', 'l', 's', ':', ' ', 'V', 'a', 'r', 'i', 'a', 'n', 't', ' ', '=', ' ', 'E', 'm', 'p', 't', 'y', 'V', 'a', 'r', ')', ':', ' ', 'V', 'a', 'r', 'i', 'a', 'n', 't', 0, 
	HB_P_PUSHSTRSHORT, 21,	/* 21 */
	'M', 'y', ' ', 'L', 'o', 'v', 'e', 'l', 'y', ' ', 'F', 'u', 'n', 'c', 't', 'i', 'o', 'n', 's', '!', 0, 
	HB_P_PUSHSTRSHORT, 29,	/* 29 */
	'I', 't', 39, 's', ' ', 'a', ' ', 'X', 'B', 'a', 's', 'e', ' ', 'S', 't', 'r', '(', ')', ' ', 'f', 'u', 'n', 'c', 't', 'i', 'o', 'n', '!', 0, 
	HB_P_SENDSHORT, 3,
	HB_P_POP,
/* 02342 */ HB_P_LINEOFFSET, 127,	/* 149 */
	HB_P_MESSAGE, 74, 0,	/* ACTIVATE */
	HB_P_PUSHLOCALNEAR, 3,	/* ODLG */
	HB_P_MESSAGE, 75, 0,	/* BLCLICKED */
	HB_P_PUSHLOCALNEAR, 3,	/* ODLG */
	HB_P_SENDSHORT, 0,
	HB_P_MESSAGE, 76, 0,	/* BMOVED */
	HB_P_PUSHLOCALNEAR, 3,	/* ODLG */
	HB_P_SENDSHORT, 0,
	HB_P_MESSAGE, 77, 0,	/* BPAINTED */
	HB_P_PUSHLOCALNEAR, 3,	/* ODLG */
	HB_P_SENDSHORT, 0,
	HB_P_TRUE,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHBLOCK, 13, 0,	/* 13 */
	1, 0,	/* number of local parameters (1) */
	0, 0,	/* number of local variables (0) */
	HB_P_PUSHSYMNEAR, 78,	/* GENERATEITEMS */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_ENDBLOCK,
	HB_P_MESSAGE, 79, 0,	/* BRCLICKED */
	HB_P_PUSHLOCALNEAR, 3,	/* ODLG */
	HB_P_SENDSHORT, 0,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_SENDSHORT, 10,
	HB_P_POP,
/* 02398 */ HB_P_LINEOFFSET, 129,	/* 151 */
	HB_P_PUSHSYMNEAR, 80,	/* UNLOADFR */
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 0,
/* 02405 */ HB_P_LINEOFFSET, 131,	/* 153 */
	HB_P_PUSHNIL,
	HB_P_RETVALUE,
	HB_P_ENDPROC
/* 02410 */
   };

   hb_vmExecute( pcode, symbols );
}

HB_FUNC( GENERATEITEMS )
{
   static const BYTE pcode[] =
   {
	HB_P_FRAME, 2, 0,	/* locals, params */
/* 00003 */ HB_P_BASELINE, 160, 0,	/* 160 */
	HB_P_ARRAYGEN, 0, 0,	/* 0 */
	HB_P_POPLOCALNEAR, 1,	/* AITEM */
	HB_P_PUSHVARIABLE, 34, 0,	/* CCOMBO */
	HB_P_POPLOCALNEAR, 2,	/* CITEM */
/* 00016 */ HB_P_LINEOFFSET, 1,	/* 161 */
	HB_P_PUSHSYMNEAR, 81,	/* DIRECTORY */
	HB_P_PUSHNIL,
	HB_P_PUSHVARIABLE, 16, 0,	/* RESDIR */
	HB_P_PUSHSTRSHORT, 6,	/* 6 */
	'*', '.', 'x', 'm', 'l', 0, 
	HB_P_PLUS,
	HB_P_FUNCTIONSHORT, 1,
	HB_P_POPVARIABLE, 82, 0,	/* ATMP */
/* 00038 */ HB_P_LINEOFFSET, 2,	/* 162 */
	HB_P_ONE,
	HB_P_POPVARIABLE, 83, 0,	/* X */
	HB_P_PUSHVARIABLE, 83, 0,	/* X */
	HB_P_PUSHSYMNEAR, 84,	/* LEN */
	HB_P_PUSHNIL,
	HB_P_PUSHVARIABLE, 82, 0,	/* ATMP */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_LESSEQUAL,
	HB_P_JUMPFALSENEAR, 54,	/* 54 (abs: 00110) */
/* 00058 */ HB_P_LINEOFFSET, 3,	/* 163 */
	HB_P_PUSHSYMNEAR, 85,	/* AADD */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 1,	/* AITEM */
	HB_P_PUSHSYMNEAR, 86,	/* SUBSTR */
	HB_P_PUSHNIL,
	HB_P_PUSHMEMVAR, 82, 0,	/* ATMP */
	HB_P_PUSHVARIABLE, 83, 0,	/* X */
	HB_P_ARRAYPUSH,
	HB_P_ONE,
	HB_P_ARRAYPUSH,
	HB_P_ONE,
	HB_P_PUSHSYMNEAR, 84,	/* LEN */
	HB_P_PUSHNIL,
	HB_P_PUSHMEMVAR, 82, 0,	/* ATMP */
	HB_P_PUSHVARIABLE, 83, 0,	/* X */
	HB_P_ARRAYPUSH,
	HB_P_ONE,
	HB_P_ARRAYPUSH,
	HB_P_FUNCTIONSHORT, 1,
	HB_P_ADDINT, 252, 255,	/* -4*/
	HB_P_FUNCTIONSHORT, 3,
	HB_P_DOSHORT, 2,
/* 00099 */ HB_P_LINEOFFSET, 4,	/* 164 */
	HB_P_PUSHVARIABLE, 83, 0,	/* X */
	HB_P_INC,
	HB_P_POPVARIABLE, 83, 0,	/* X */
	HB_P_JUMPNEAR, 192,	/* -64 (abs: 00044) */
/* 00110 */ HB_P_LINEOFFSET, 5,	/* 165 */
	HB_P_MESSAGE, 87, 0,	/* SETITEMS */
	HB_P_PUSHVARIABLE, 47, 0,	/* OCOMBO */
	HB_P_PUSHLOCALNEAR, 1,	/* AITEM */
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00123 */ HB_P_LINEOFFSET, 6,	/* 166 */
	HB_P_MESSAGE, 88, 0,	/* SET */
	HB_P_PUSHVARIABLE, 47, 0,	/* OCOMBO */
	HB_P_PUSHLOCALNEAR, 2,	/* CITEM */
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00136 */ HB_P_LINEOFFSET, 8,	/* 168 */
	HB_P_PUSHNIL,
	HB_P_RETVALUE,
	HB_P_ENDPROC
/* 00141 */
   };

   hb_vmExecute( pcode, symbols );
}

HB_FUNC( UNLOADFR )
{
   static const BYTE pcode[] =
   {
/* 00000 */ HB_P_BASELINE, 175, 0,	/* 175 */
	HB_P_MESSAGE, 89, 0,	/* DESTROYFR */
	HB_P_PUSHVARIABLE, 5, 0,	/* FRPRN */
	HB_P_SENDSHORT, 0,
	HB_P_POP,
/* 00012 */ HB_P_LINEOFFSET, 2,	/* 177 */
	HB_P_PUSHNIL,
	HB_P_RETVALUE,
	HB_P_ENDPROC
/* 00017 */
   };

   hb_vmExecute( pcode, symbols );
}

HB_FUNC( DOFRACTION )
{
   static const BYTE pcode[] =
   {
	HB_P_FRAME, 1, 2,	/* locals, params */
/* 00003 */ HB_P_BASELINE, 182, 0,	/* 182 */
	HB_P_FALSE,
	HB_P_POPLOCALNEAR, 3,	/* LNOTOPENED */
/* 00009 */ HB_P_LINEOFFSET, 2,	/* 184 */
	HB_P_PUSHSYMNEAR, 8,	/* __MVPRIVATE */
	HB_P_PUSHNIL,
	HB_P_PUSHSYMNEAR, 91,	/* CEXPOBJ */
	HB_P_PUSHSYMNEAR, 92,	/* CEXPFILE */
	HB_P_PUSHSYMNEAR, 93,	/* LEXPOPT */
	HB_P_PUSHSYMNEAR, 94,	/* LEXPOPEN */
	HB_P_PUSHSYMNEAR, 95,	/* CEXTENTION */
	HB_P_DOSHORT, 5,
/* 00026 */ HB_P_LINEOFFSET, 4,	/* 186 */
	HB_P_PUSHLOCALNEAR, 2,	/* LPREPARED */
	HB_P_PUSHNIL,
	HB_P_NOTEQUAL,
	HB_P_JUMPFALSENEAR, 6,	/* 6 (abs: 00038) */
	HB_P_PUSHLOCALNEAR, 2,	/* LPREPARED */
	HB_P_JUMPNEAR, 3,	/* 3 (abs: 00039) */
	HB_P_FALSE,
	HB_P_POPLOCALNEAR, 2,	/* LPREPARED */
/* 00041 */ HB_P_LINEOFFSET, 5,	/* 187 */
	HB_P_FALSE,
	HB_P_PUSHLOCALNEAR, 2,	/* LPREPARED */
	HB_P_JUMPTRUENEAR, 7,	/* 7 (abs: 00053) */
	HB_P_POP,
	HB_P_PUSHLOCALNEAR, 1,	/* CFILENAME */
	HB_P_PUSHNIL,
	HB_P_NOTEQUAL,
	HB_P_JUMPFALSENEAR, 19,	/* 19 (abs: 00072) */
/* 00055 */ HB_P_LINEOFFSET, 6,	/* 188 */
	HB_P_MESSAGE, 96, 0,	/* LOADFROMFILE */
	HB_P_PUSHVARIABLE, 5, 0,	/* FRPRN */
	HB_P_PUSHVARIABLE, 14, 0,	/* REPDIR */
	HB_P_PUSHLOCALNEAR, 1,	/* CFILENAME */
	HB_P_PLUS,
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00072 */ HB_P_LINEOFFSET, 9,	/* 191 */
	HB_P_MESSAGE, 97, 0,	/* SETNAME */
	HB_P_MESSAGE, 98, 0,	/* REPORTOPTIONS */
	HB_P_PUSHVARIABLE, 5, 0,	/* FRPRN */
	HB_P_SENDSHORT, 0,
	HB_P_SENDSHORT, 0,
	HB_P_POPVARIABLE, 36, 0,	/* CNOME */
/* 00090 */ HB_P_LINEOFFSET, 10,	/* 192 */
	HB_P_MESSAGE, 99, 0,	/* SETDESCRIPTION */
	HB_P_MESSAGE, 98, 0,	/* REPORTOPTIONS */
	HB_P_PUSHVARIABLE, 5, 0,	/* FRPRN */
	HB_P_SENDSHORT, 0,
	HB_P_SENDSHORT, 0,
	HB_P_POPVARIABLE, 37, 0,	/* CDESC */
/* 00108 */ HB_P_LINEOFFSET, 11,	/* 193 */
	HB_P_MESSAGE, 100, 0,	/* REFRESH */
	HB_P_PUSHVARIABLE, 61, 0,	/* ONOME */
	HB_P_SENDSHORT, 0,
	HB_P_POP,
/* 00119 */ HB_P_LINEOFFSET, 12,	/* 194 */
	HB_P_MESSAGE, 100, 0,	/* REFRESH */
	HB_P_PUSHVARIABLE, 63, 0,	/* ODESC */
	HB_P_SENDSHORT, 0,
	HB_P_POP,
/* 00130 */ HB_P_LINEOFFSET, 16,	/* 198 */
	HB_P_PUSHVARIABLE, 7, 0,	/* NACTION */
	HB_P_ONE,
	HB_P_EXACTLYEQUAL,
	HB_P_JUMPFALSENEAR, 16,	/* 16 (abs: 00153) */
/* 00139 */ HB_P_LINEOFFSET, 17,	/* 199 */
	HB_P_MESSAGE, 101, 0,	/* SHOWREPORT */
	HB_P_PUSHVARIABLE, 5, 0,	/* FRPRN */
	HB_P_SENDSHORT, 0,
	HB_P_POP,
	HB_P_JUMP, 221, 2,	/* 733 (abs: 00883) */
/* 00153 */ HB_P_LINEOFFSET, 18,	/* 200 */
	HB_P_PUSHVARIABLE, 7, 0,	/* NACTION */
	HB_P_PUSHBYTE, 2,	/* 2 */
	HB_P_EXACTLYEQUAL,
	HB_P_JUMPFALSENEAR, 16,	/* 16 (abs: 00177) */
/* 00163 */ HB_P_LINEOFFSET, 19,	/* 201 */
	HB_P_MESSAGE, 102, 0,	/* DESIGNREPORT */
	HB_P_PUSHVARIABLE, 5, 0,	/* FRPRN */
	HB_P_SENDSHORT, 0,
	HB_P_POP,
	HB_P_JUMP, 197, 2,	/* 709 (abs: 00883) */
/* 00177 */ HB_P_LINEOFFSET, 20,	/* 202 */
	HB_P_PUSHVARIABLE, 7, 0,	/* NACTION */
	HB_P_PUSHBYTE, 3,	/* 3 */
	HB_P_EXACTLYEQUAL,
	HB_P_JUMPFALSENEAR, 106,	/* 106 (abs: 00291) */
/* 00187 */ HB_P_LINEOFFSET, 21,	/* 203 */
	HB_P_MESSAGE, 103, 0,	/* SETPROPERTY */
	HB_P_PUSHVARIABLE, 5, 0,	/* FRPRN */
	HB_P_PUSHSTRSHORT, 7,	/* 7 */
	'R', 'e', 'p', 'o', 'r', 't', 0, 
	HB_P_PUSHSTRSHORT, 13,	/* 13 */
	'S', 'h', 'o', 'w', 'P', 'r', 'o', 'g', 'r', 'e', 's', 's', 0, 
	HB_P_FALSE,
	HB_P_SENDSHORT, 3,
	HB_P_POP,
/* 00223 */ HB_P_LINEOFFSET, 22,	/* 204 */
	HB_P_PUSHLOCALNEAR, 2,	/* LPREPARED */
	HB_P_JUMPTRUENEAR, 13,	/* 13 (abs: 00240) */
/* 00229 */ HB_P_LINEOFFSET, 23,	/* 205 */
	HB_P_MESSAGE, 104, 0,	/* PREPAREREPORT */
	HB_P_PUSHVARIABLE, 5, 0,	/* FRPRN */
	HB_P_SENDSHORT, 0,
	HB_P_POP,
/* 00240 */ HB_P_LINEOFFSET, 25,	/* 207 */
	HB_P_MESSAGE, 105, 0,	/* PRINT */
	HB_P_PUSHVARIABLE, 5, 0,	/* FRPRN */
	HB_P_TRUE,
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00252 */ HB_P_LINEOFFSET, 26,	/* 208 */
	HB_P_MESSAGE, 103, 0,	/* SETPROPERTY */
	HB_P_PUSHVARIABLE, 5, 0,	/* FRPRN */
	HB_P_PUSHSTRSHORT, 7,	/* 7 */
	'R', 'e', 'p', 'o', 'r', 't', 0, 
	HB_P_PUSHSTRSHORT, 13,	/* 13 */
	'S', 'h', 'o', 'w', 'P', 'r', 'o', 'g', 'r', 'e', 's', 's', 0, 
	HB_P_TRUE,
	HB_P_SENDSHORT, 3,
	HB_P_POP,
	HB_P_JUMP, 83, 2,	/* 595 (abs: 00883) */
/* 00291 */ HB_P_LINEOFFSET, 27,	/* 209 */
	HB_P_PUSHVARIABLE, 7, 0,	/* NACTION */
	HB_P_PUSHBYTE, 4,	/* 4 */
	HB_P_EXACTLYEQUAL,
	HB_P_JUMPFALSE, 72, 2,	/* 584 (abs: 00883) */
/* 00302 */ HB_P_LINEOFFSET, 28,	/* 210 */
	HB_P_PUSHSYMNEAR, 106,	/* GETEXPORTOBJECT */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_JUMPFALSE, 62, 2,	/* 574 (abs: 00883) */
/* 00312 */ HB_P_LINEOFFSET, 29,	/* 211 */
	HB_P_MESSAGE, 103, 0,	/* SETPROPERTY */
	HB_P_PUSHVARIABLE, 5, 0,	/* FRPRN */
	HB_P_PUSHSTRSHORT, 7,	/* 7 */
	'R', 'e', 'p', 'o', 'r', 't', 0, 
	HB_P_PUSHSTRSHORT, 13,	/* 13 */
	'S', 'h', 'o', 'w', 'P', 'r', 'o', 'g', 'r', 'e', 's', 's', 0, 
	HB_P_FALSE,
	HB_P_SENDSHORT, 3,
	HB_P_POP,
/* 00348 */ HB_P_LINEOFFSET, 30,	/* 212 */
	HB_P_PUSHLOCALNEAR, 2,	/* LPREPARED */
	HB_P_JUMPTRUENEAR, 13,	/* 13 (abs: 00365) */
/* 00354 */ HB_P_LINEOFFSET, 31,	/* 213 */
	HB_P_MESSAGE, 104, 0,	/* PREPAREREPORT */
	HB_P_PUSHVARIABLE, 5, 0,	/* FRPRN */
	HB_P_SENDSHORT, 0,
	HB_P_POP,
/* 00365 */ HB_P_LINEOFFSET, 33,	/* 215 */
	HB_P_MESSAGE, 103, 0,	/* SETPROPERTY */
	HB_P_PUSHVARIABLE, 5, 0,	/* FRPRN */
	HB_P_PUSHVARIABLE, 91, 0,	/* CEXPOBJ */
	HB_P_PUSHSTRSHORT, 11,	/* 11 */
	'S', 'h', 'o', 'w', 'D', 'i', 'a', 'l', 'o', 'g', 0, 
	HB_P_PUSHVARIABLE, 93, 0,	/* LEXPOPT */
	HB_P_SENDSHORT, 3,
	HB_P_POP,
/* 00395 */ HB_P_LINEOFFSET, 34,	/* 216 */
	HB_P_FALSE,
	HB_P_PUSHVARIABLE, 91, 0,	/* CEXPOBJ */
	HB_P_PUSHSTRSHORT, 11,	/* 11 */
	'M', 'a', 'i', 'l', 'E', 'x', 'p', 'o', 'r', 't', 0, 
	HB_P_EQUAL,
	HB_P_JUMPFALSENEAR, 7,	/* 7 (abs: 00422) */
	HB_P_POP,
	HB_P_PUSHVARIABLE, 93, 0,	/* LEXPOPT */
	HB_P_NOT,
	HB_P_JUMPFALSENEAR, 30,	/* 30 (abs: 00452) */
/* 00424 */ HB_P_LINEOFFSET, 35,	/* 217 */
	HB_P_MESSAGE, 103, 0,	/* SETPROPERTY */
	HB_P_PUSHVARIABLE, 5, 0,	/* FRPRN */
	HB_P_PUSHVARIABLE, 91, 0,	/* CEXPOBJ */
	HB_P_PUSHSTRSHORT, 11,	/* 11 */
	'S', 'h', 'o', 'w', 'D', 'i', 'a', 'l', 'o', 'g', 0, 
	HB_P_TRUE,
	HB_P_SENDSHORT, 3,
	HB_P_POP,
/* 00452 */ HB_P_LINEOFFSET, 37,	/* 219 */
	HB_P_PUSHSYMNEAR, 107,	/* ASCAN */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 10,	/* 10 */
	'X', 'L', 'S', 'E', 'x', 'p', 'o', 'r', 't', 0, 
	HB_P_PUSHSTRSHORT, 10,	/* 10 */
	'X', 'M', 'L', 'E', 'x', 'p', 'o', 'r', 't', 0, 
	HB_P_ARRAYGEN, 2, 0,	/* 2 */
	HB_P_PUSHVARIABLE, 91, 0,	/* CEXPOBJ */
	HB_P_FUNCTIONSHORT, 2,
	HB_P_ZERO,
	HB_P_GREATER,
	HB_P_JUMPFALSENEAR, 45,	/* 45 (abs: 00536) */
/* 00493 */ HB_P_LINEOFFSET, 38,	/* 220 */
	HB_P_MESSAGE, 103, 0,	/* SETPROPERTY */
	HB_P_PUSHVARIABLE, 5, 0,	/* FRPRN */
	HB_P_PUSHVARIABLE, 91, 0,	/* CEXPOBJ */
	HB_P_PUSHSTRSHORT, 21,	/* 21 */
	'O', 'p', 'e', 'n', 'E', 'x', 'c', 'e', 'l', 'A', 'f', 't', 'e', 'r', 'E', 'x', 'p', 'o', 'r', 't', 0, 
	HB_P_PUSHVARIABLE, 94, 0,	/* LEXPOPEN */
	HB_P_SENDSHORT, 3,
	HB_P_POP,
	HB_P_JUMP, 142, 0,	/* 142 (abs: 00675) */
/* 00536 */ HB_P_LINEOFFSET, 41,	/* 223 */
	HB_P_PUSHSYMNEAR, 107,	/* ASCAN */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 10,	/* 10 */
	'B', 'M', 'P', 'E', 'x', 'p', 'o', 'r', 't', 0, 
	HB_P_PUSHSTRSHORT, 11,	/* 11 */
	'T', 'I', 'F', 'F', 'E', 'x', 'p', 'o', 'r', 't', 0, 
	HB_P_PUSHSTRSHORT, 11,	/* 11 */
	'J', 'P', 'E', 'G', 'E', 'x', 'p', 'o', 'r', 't', 0, 
	HB_P_PUSHSTRSHORT, 10,	/* 10 */
	'G', 'I', 'F', 'E', 'x', 'p', 'o', 'r', 't', 0, 
	HB_P_PUSHSTRSHORT, 16,	/* 16 */
	'D', 'o', 't', 'M', 'a', 't', 'r', 'i', 'x', 'E', 'x', 'p', 'o', 'r', 't', 0, 
	HB_P_PUSHSTRSHORT, 10,	/* 10 */
	'T', 'X', 'T', 'E', 'x', 'p', 'o', 'r', 't', 0, 
	HB_P_ARRAYGEN, 6, 0,	/* 6 */
	HB_P_PUSHVARIABLE, 91, 0,	/* CEXPOBJ */
	HB_P_FUNCTIONSHORT, 2,
	HB_P_ZERO,
	HB_P_GREATER,
	HB_P_JUMPFALSENEAR, 9,	/* 9 (abs: 00640) */
/* 00633 */ HB_P_LINEOFFSET, 42,	/* 224 */
	HB_P_TRUE,
	HB_P_POPLOCALNEAR, 3,	/* LNOTOPENED */
	HB_P_JUMPNEAR, 37,	/* 37 (abs: 00675) */
/* 00640 */ HB_P_LINEOFFSET, 44,	/* 226 */
	HB_P_MESSAGE, 103, 0,	/* SETPROPERTY */
	HB_P_PUSHVARIABLE, 5, 0,	/* FRPRN */
	HB_P_PUSHVARIABLE, 91, 0,	/* CEXPOBJ */
	HB_P_PUSHSTRSHORT, 16,	/* 16 */
	'O', 'p', 'e', 'n', 'A', 'f', 't', 'e', 'r', 'E', 'x', 'p', 'o', 'r', 't', 0, 
	HB_P_PUSHVARIABLE, 94, 0,	/* LEXPOPEN */
	HB_P_SENDSHORT, 3,
	HB_P_POP,
/* 00675 */ HB_P_LINEOFFSET, 47,	/* 229 */
	HB_P_FALSE,
	HB_P_PUSHVARIABLE, 94, 0,	/* LEXPOPEN */
	HB_P_JUMPFALSENEAR, 6,	/* 6 (abs: 00687) */
	HB_P_POP,
	HB_P_PUSHLOCALNEAR, 3,	/* LNOTOPENED */
	HB_P_NOT,
	HB_P_JUMPFALSENEAR, 85,	/* 85 (abs: 00772) */
/* 00689 */ HB_P_LINEOFFSET, 48,	/* 230 */
	HB_P_PUSHVARIABLE, 91, 0,	/* CEXPOBJ */
	HB_P_PUSHSTRSHORT, 17,	/* 17 */
	'S', 'i', 'm', 'p', 'l', 'e', 'T', 'e', 'x', 't', 'E', 'x', 'p', 'o', 'r', 't', 0, 
	HB_P_NOTEQUAL,
	HB_P_JUMPFALSENEAR, 20,	/* 20 (abs: 00734) */
/* 00716 */ HB_P_LINEOFFSET, 49,	/* 231 */
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'.', 0, 
	HB_P_PUSHVARIABLE, 91, 0,	/* CEXPOBJ */
	HB_P_LEFT, 3, 0,	/* 3 */
	HB_P_PLUS,
	HB_P_POPVARIABLE, 95, 0,	/* CEXTENTION */
	HB_P_JUMPNEAR, 14,	/* 14 (abs: 00746) */
/* 00734 */ HB_P_LINEOFFSET, 51,	/* 233 */
	HB_P_PUSHSTRSHORT, 5,	/* 5 */
	'.', 'T', 'X', 'T', 0, 
	HB_P_POPVARIABLE, 95, 0,	/* CEXTENTION */
/* 00746 */ HB_P_LINEOFFSET, 53,	/* 235 */
	HB_P_PUSHVARIABLE, 92, 0,	/* CEXPFILE */
	HB_P_RIGHT, 4, 0,	/* 4 */
	HB_P_PUSHVARIABLE, 95, 0,	/* CEXTENTION */
	HB_P_NOTEQUAL,
	HB_P_JUMPFALSENEAR, 14,	/* 14 (abs: 00772) */
/* 00760 */ HB_P_LINEOFFSET, 54,	/* 236 */
	HB_P_PUSHVARIABLE, 92, 0,	/* CEXPFILE */
	HB_P_PUSHVARIABLE, 95, 0,	/* CEXTENTION */
	HB_P_PLUS,
	HB_P_POPVARIABLE, 92, 0,	/* CEXPFILE */
/* 00772 */ HB_P_LINEOFFSET, 57,	/* 239 */
	HB_P_MESSAGE, 103, 0,	/* SETPROPERTY */
	HB_P_PUSHVARIABLE, 5, 0,	/* FRPRN */
	HB_P_PUSHVARIABLE, 91, 0,	/* CEXPOBJ */
	HB_P_PUSHSTRSHORT, 9,	/* 9 */
	'F', 'i', 'l', 'e', 'N', 'a', 'm', 'e', 0, 
	HB_P_PUSHVARIABLE, 92, 0,	/* CEXPFILE */
	HB_P_SENDSHORT, 3,
	HB_P_POP,
/* 00800 */ HB_P_LINEOFFSET, 58,	/* 240 */
	HB_P_MESSAGE, 108, 0,	/* DOEXPORT */
	HB_P_PUSHVARIABLE, 5, 0,	/* FRPRN */
	HB_P_PUSHVARIABLE, 91, 0,	/* CEXPOBJ */
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00814 */ HB_P_LINEOFFSET, 59,	/* 241 */
	HB_P_FALSE,
	HB_P_PUSHVARIABLE, 94, 0,	/* LEXPOPEN */
	HB_P_JUMPFALSENEAR, 5,	/* 5 (abs: 00825) */
	HB_P_POP,
	HB_P_PUSHLOCALNEAR, 3,	/* LNOTOPENED */
	HB_P_JUMPFALSENEAR, 22,	/* 22 (abs: 00847) */
/* 00827 */ HB_P_LINEOFFSET, 60,	/* 242 */
	HB_P_PUSHSYMNEAR, 109,	/* MSGALERT */
	HB_P_PUSHNIL,
	HB_P_PUSHVARIABLE, 110, 0,	/* _CNOOPEN */
	HB_P_PUSHSTRSHORT, 8,	/* 8 */
	'A', 't', 'e', 'n', 231, 227, 'o', 0, 
	HB_P_DOSHORT, 2,
/* 00847 */ HB_P_LINEOFFSET, 62,	/* 244 */
	HB_P_MESSAGE, 103, 0,	/* SETPROPERTY */
	HB_P_PUSHVARIABLE, 5, 0,	/* FRPRN */
	HB_P_PUSHSTRSHORT, 7,	/* 7 */
	'R', 'e', 'p', 'o', 'r', 't', 0, 
	HB_P_PUSHSTRSHORT, 13,	/* 13 */
	'S', 'h', 'o', 'w', 'P', 'r', 'o', 'g', 'r', 'e', 's', 's', 0, 
	HB_P_TRUE,
	HB_P_SENDSHORT, 3,
	HB_P_POP,
/* 00883 */ HB_P_LINEOFFSET, 66,	/* 248 */
	HB_P_PUSHNIL,
	HB_P_RETVALUE,
	HB_P_ENDPROC
/* 00888 */
   };

   hb_vmExecute( pcode, symbols );
}

HB_FUNC( DOSIMPLELIST )
{
   static const BYTE pcode[] =
   {
/* 00000 */ HB_P_BASELINE, 253, 0,	/* 253 */
	HB_P_MESSAGE, 111, 0,	/* SETWORKAREA */
	HB_P_PUSHVARIABLE, 5, 0,	/* FRPRN */
	HB_P_PUSHSTRSHORT, 10,	/* 10 */
	'C', 'u', 's', 't', 'o', 'm', 'e', 'r', 's', 0, 
	HB_P_ONE,
	HB_P_SENDSHORT, 2,
	HB_P_POP,
/* 00025 */ HB_P_LINEOFFSET, 1,	/* 254 */
	HB_P_MESSAGE, 112, 0,	/* SETFIELDALIASES */
	HB_P_PUSHVARIABLE, 5, 0,	/* FRPRN */
	HB_P_PUSHSTRSHORT, 10,	/* 10 */
	'C', 'u', 's', 't', 'o', 'm', 'e', 'r', 's', 0, 
	HB_P_PUSHSTRSHORT, 55,	/* 55 */
	'C', 'U', 'S', 'T', 'N', 'O', '=', 'C', 'u', 's', 't', ' ', 'N', 'o', ';', 'C', 'o', 'm', 'p', 'a', 'n', 'y', ';', 'A', 'D', 'D', 'R', '1', '=', 'A', 'd', 'd', 'r', 'e', 's', 's', ';', 'P', 'h', 'o', 'n', 'e', ';', 'F', 'a', 'x', ';', 'C', 'o', 'n', 't', 'a', 'c', 't', 0, 
	HB_P_SENDSHORT, 2,
	HB_P_POP,
/* 00105 */ HB_P_LINEOFFSET, 2,	/* 255 */
	HB_P_TRUE,
	HB_P_POPVARIABLE, 6, 0,	/* LSHOWCUSTNAME */
/* 00111 */ HB_P_LINEOFFSET, 3,	/* 256 */
	HB_P_PUSHSYMNEAR, 90,	/* DOFRACTION */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 6,	/* 6 */
	'1', '.', 'f', 'r', '3', 0, 
	HB_P_DOSHORT, 1,
/* 00126 */ HB_P_LINEOFFSET, 4,	/* 257 */
	HB_P_MESSAGE, 113, 0,	/* CLEARDATASETS */
	HB_P_PUSHVARIABLE, 5, 0,	/* FRPRN */
	HB_P_SENDSHORT, 0,
	HB_P_POP,
/* 00137 */ HB_P_LINEOFFSET, 5,	/* 258 */
	HB_P_FALSE,
	HB_P_POPVARIABLE, 6, 0,	/* LSHOWCUSTNAME */
/* 00143 */ HB_P_LINEOFFSET, 7,	/* 260 */
	HB_P_ENDPROC
/* 00146 */
   };

   hb_vmExecute( pcode, symbols );
}

HB_FUNC( DOSIMPLEGROUP )
{
   static const BYTE pcode[] =
   {
/* 00000 */ HB_P_BASELINE, 9, 1,	/* 265 */
	HB_P_MESSAGE, 111, 0,	/* SETWORKAREA */
	HB_P_PUSHVARIABLE, 5, 0,	/* FRPRN */
	HB_P_PUSHSTRSHORT, 10,	/* 10 */
	'C', 'u', 's', 't', 'o', 'm', 'e', 'r', 's', 0, 
	HB_P_ONE,
	HB_P_SENDSHORT, 2,
	HB_P_POP,
/* 00025 */ HB_P_LINEOFFSET, 1,	/* 266 */
	HB_P_MESSAGE, 112, 0,	/* SETFIELDALIASES */
	HB_P_PUSHVARIABLE, 5, 0,	/* FRPRN */
	HB_P_PUSHSTRSHORT, 10,	/* 10 */
	'C', 'u', 's', 't', 'o', 'm', 'e', 'r', 's', 0, 
	HB_P_PUSHSTRSHORT, 55,	/* 55 */
	'C', 'U', 'S', 'T', 'N', 'O', '=', 'C', 'u', 's', 't', ' ', 'N', 'o', ';', 'C', 'o', 'm', 'p', 'a', 'n', 'y', ';', 'A', 'D', 'D', 'R', '1', '=', 'A', 'd', 'd', 'r', 'e', 's', 's', ';', 'P', 'h', 'o', 'n', 'e', ';', 'F', 'a', 'x', ';', 'C', 'o', 'n', 't', 'a', 'c', 't', 0, 
	HB_P_SENDSHORT, 2,
	HB_P_POP,
/* 00105 */ HB_P_LINEOFFSET, 2,	/* 267 */
	HB_P_TRUE,
	HB_P_POPVARIABLE, 6, 0,	/* LSHOWCUSTNAME */
/* 00111 */ HB_P_LINEOFFSET, 3,	/* 268 */
	HB_P_PUSHSYMNEAR, 90,	/* DOFRACTION */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 8,	/* 8 */
	'2', 'g', 'r', '.', 'f', 'r', '3', 0, 
	HB_P_DOSHORT, 1,
/* 00128 */ HB_P_LINEOFFSET, 4,	/* 269 */
	HB_P_MESSAGE, 113, 0,	/* CLEARDATASETS */
	HB_P_PUSHVARIABLE, 5, 0,	/* FRPRN */
	HB_P_SENDSHORT, 0,
	HB_P_POP,
/* 00139 */ HB_P_LINEOFFSET, 5,	/* 270 */
	HB_P_FALSE,
	HB_P_POPVARIABLE, 6, 0,	/* LSHOWCUSTNAME */
/* 00145 */ HB_P_LINEOFFSET, 7,	/* 272 */
	HB_P_ENDPROC
/* 00148 */
   };

   hb_vmExecute( pcode, symbols );
}

HB_FUNC( DOMORECOMPLEX )
{
   static const BYTE pcode[] =
   {
/* 00000 */ HB_P_BASELINE, 21, 1,	/* 277 */
	HB_P_PUSHSYMNEAR, 114,	/* DBSELECTAREA */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 6,	/* 6 */
	'I', 't', 'e', 'm', 's', 0, 
	HB_P_DOSHORT, 1,
/* 00016 */ HB_P_LINEOFFSET, 1,	/* 278 */
	HB_P_PUSHSYMNEAR, 30,	/* ORDSETFOCUS */
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 2,	/* 2 */
	HB_P_DOSHORT, 1,
/* 00025 */ HB_P_LINEOFFSET, 2,	/* 279 */
	HB_P_TRUE,
	HB_P_POPVARIABLE, 6, 0,	/* LSHOWCUSTNAME */
/* 00031 */ HB_P_LINEOFFSET, 3,	/* 280 */
	HB_P_MESSAGE, 111, 0,	/* SETWORKAREA */
	HB_P_PUSHVARIABLE, 5, 0,	/* FRPRN */
	HB_P_PUSHSTRSHORT, 10,	/* 10 */
	'C', 'u', 's', 't', 'o', 'm', 'e', 'r', 's', 0, 
	HB_P_ONE,
	HB_P_SENDSHORT, 2,
	HB_P_POP,
/* 00055 */ HB_P_LINEOFFSET, 4,	/* 281 */
	HB_P_MESSAGE, 112, 0,	/* SETFIELDALIASES */
	HB_P_PUSHVARIABLE, 5, 0,	/* FRPRN */
	HB_P_PUSHSTRSHORT, 10,	/* 10 */
	'C', 'u', 's', 't', 'o', 'm', 'e', 'r', 's', 0, 
	HB_P_PUSHSTRSHORT, 55,	/* 55 */
	'C', 'U', 'S', 'T', 'N', 'O', '=', 'C', 'u', 's', 't', ' ', 'N', 'o', ';', 'C', 'o', 'm', 'p', 'a', 'n', 'y', ';', 'A', 'D', 'D', 'R', '1', '=', 'A', 'd', 'd', 'r', 'e', 's', 's', ';', 'P', 'h', 'o', 'n', 'e', ';', 'F', 'a', 'x', ';', 'C', 'o', 'n', 't', 'a', 'c', 't', 0, 
	HB_P_SENDSHORT, 2,
	HB_P_POP,
/* 00135 */ HB_P_LINEOFFSET, 5,	/* 282 */
	HB_P_MESSAGE, 111, 0,	/* SETWORKAREA */
	HB_P_PUSHVARIABLE, 5, 0,	/* FRPRN */
	HB_P_PUSHSTRSHORT, 7,	/* 7 */
	'O', 'r', 'd', 'e', 'r', 's', 0, 
	HB_P_PUSHBYTE, 2,	/* 2 */
	HB_P_SENDSHORT, 2,
	HB_P_POP,
/* 00157 */ HB_P_LINEOFFSET, 6,	/* 283 */
	HB_P_MESSAGE, 111, 0,	/* SETWORKAREA */
	HB_P_PUSHVARIABLE, 5, 0,	/* FRPRN */
	HB_P_PUSHSTRSHORT, 6,	/* 6 */
	'I', 't', 'e', 'm', 's', 0, 
	HB_P_PUSHBYTE, 3,	/* 3 */
	HB_P_SENDSHORT, 2,
	HB_P_POP,
/* 00178 */ HB_P_LINEOFFSET, 7,	/* 284 */
	HB_P_MESSAGE, 111, 0,	/* SETWORKAREA */
	HB_P_PUSHVARIABLE, 5, 0,	/* FRPRN */
	HB_P_PUSHSTRSHORT, 6,	/* 6 */
	'P', 'a', 'r', 't', 's', 0, 
	HB_P_PUSHBYTE, 4,	/* 4 */
	HB_P_SENDSHORT, 2,
	HB_P_POP,
/* 00199 */ HB_P_LINEOFFSET, 8,	/* 285 */
	HB_P_MESSAGE, 115, 0,	/* SETMASTERDETAIL */
	HB_P_PUSHVARIABLE, 5, 0,	/* FRPRN */
	HB_P_PUSHSTRSHORT, 10,	/* 10 */
	'C', 'u', 's', 't', 'o', 'm', 'e', 'r', 's', 0, 
	HB_P_PUSHSTRSHORT, 7,	/* 7 */
	'O', 'r', 'd', 'e', 'r', 's', 0, 
	HB_P_PUSHBLOCKSHORT, 7,	/* 7 */
	HB_P_PUSHSYMNEAR, 116,	/* CUSTOMER */
	HB_P_PUSHALIASEDFIELDNEAR, 21,	/* CUSTNO */
	HB_P_ENDBLOCK,
	HB_P_SENDSHORT, 3,
	HB_P_POP,
/* 00238 */ HB_P_LINEOFFSET, 9,	/* 286 */
	HB_P_MESSAGE, 115, 0,	/* SETMASTERDETAIL */
	HB_P_PUSHVARIABLE, 5, 0,	/* FRPRN */
	HB_P_PUSHSTRSHORT, 7,	/* 7 */
	'O', 'r', 'd', 'e', 'r', 's', 0, 
	HB_P_PUSHSTRSHORT, 6,	/* 6 */
	'I', 't', 'e', 'm', 's', 0, 
	HB_P_PUSHBLOCKSHORT, 7,	/* 7 */
	HB_P_PUSHSYMNEAR, 117,	/* ORDERS */
	HB_P_PUSHALIASEDFIELDNEAR, 24,	/* ORDERNO */
	HB_P_ENDBLOCK,
	HB_P_SENDSHORT, 3,
	HB_P_POP,
/* 00273 */ HB_P_LINEOFFSET, 10,	/* 287 */
	HB_P_PUSHSYMNEAR, 118,	/* DBSETRELATION */
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 4,	/* 4 */
	HB_P_PUSHBLOCKSHORT, 6,	/* 6 */
	HB_P_PUSHVARIABLE, 27, 0,	/* PARTNO */
	HB_P_ENDBLOCK,
	HB_P_DOSHORT, 2,
/* 00288 */ HB_P_LINEOFFSET, 11,	/* 288 */
	HB_P_MESSAGE, 119, 0,	/* SETRESYNCPAIR */
	HB_P_PUSHVARIABLE, 5, 0,	/* FRPRN */
	HB_P_PUSHSTRSHORT, 6,	/* 6 */
	'I', 't', 'e', 'm', 's', 0, 
	HB_P_PUSHSTRSHORT, 6,	/* 6 */
	'P', 'a', 'r', 't', 's', 0, 
	HB_P_SENDSHORT, 2,
	HB_P_POP,
/* 00315 */ HB_P_LINEOFFSET, 12,	/* 289 */
	HB_P_PUSHSYMNEAR, 90,	/* DOFRACTION */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 6,	/* 6 */
	'4', '.', 'f', 'r', '3', 0, 
	HB_P_DOSHORT, 1,
/* 00330 */ HB_P_LINEOFFSET, 13,	/* 290 */
	HB_P_MESSAGE, 113, 0,	/* CLEARDATASETS */
	HB_P_PUSHVARIABLE, 5, 0,	/* FRPRN */
	HB_P_SENDSHORT, 0,
	HB_P_POP,
/* 00341 */ HB_P_LINEOFFSET, 14,	/* 291 */
	HB_P_PUSHSYMNEAR, 114,	/* DBSELECTAREA */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 6,	/* 6 */
	'I', 't', 'e', 'm', 's', 0, 
	HB_P_DOSHORT, 1,
/* 00356 */ HB_P_LINEOFFSET, 15,	/* 292 */
	HB_P_PUSHSYMNEAR, 120,	/* DBCLEARRELATION */
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 0,
/* 00363 */ HB_P_LINEOFFSET, 16,	/* 293 */
	HB_P_FALSE,
	HB_P_POPVARIABLE, 6, 0,	/* LSHOWCUSTNAME */
/* 00369 */ HB_P_LINEOFFSET, 18,	/* 295 */
	HB_P_ENDPROC
/* 00372 */
   };

   hb_vmExecute( pcode, symbols );
}

HB_FUNC( DOINFR_MORECOMPLEX )
{
   static const BYTE pcode[] =
   {
/* 00000 */ HB_P_BASELINE, 44, 1,	/* 300 */
	HB_P_PUSHSYMNEAR, 90,	/* DOFRACTION */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 7,	/* 7 */
	'm', 'd', '.', 'f', 'r', '3', 0, 
	HB_P_DOSHORT, 1,
/* 00017 */ HB_P_LINEOFFSET, 2,	/* 302 */
	HB_P_ENDPROC
/* 00020 */
   };

   hb_vmExecute( pcode, symbols );
}

HB_FUNC( MYMANUALREPORT )
{
   static const BYTE pcode[] =
   {
/* 00000 */ HB_P_BASELINE, 53, 1,	/* 309 */
	HB_P_MESSAGE, 122, 0,	/* SETDEFAULTFONTPROPERTY */
	HB_P_PUSHVARIABLE, 5, 0,	/* FRPRN */
	HB_P_PUSHSTRSHORT, 5,	/* 5 */
	'N', 'a', 'm', 'e', 0, 
	HB_P_PUSHSTRSHORT, 16,	/* 16 */
	'T', 'i', 'm', 'e', 's', ' ', 'N', 'e', 'w', ' ', 'R', 'o', 'm', 'a', 'n', 0, 
	HB_P_SENDSHORT, 2,
	HB_P_POP,
/* 00037 */ HB_P_LINEOFFSET, 1,	/* 310 */
	HB_P_MESSAGE, 122, 0,	/* SETDEFAULTFONTPROPERTY */
	HB_P_PUSHVARIABLE, 5, 0,	/* FRPRN */
	HB_P_PUSHSTRSHORT, 5,	/* 5 */
	'S', 'i', 'z', 'e', 0, 
	HB_P_PUSHBYTE, 16,	/* 16 */
	HB_P_SENDSHORT, 2,
	HB_P_POP,
/* 00057 */ HB_P_LINEOFFSET, 3,	/* 312 */
	HB_P_MESSAGE, 123, 0,	/* MEMOAT */
	HB_P_PUSHVARIABLE, 5, 0,	/* FRPRN */
	HB_P_PUSHSTRSHORT, 32,	/* 32 */
	'S', 'o', 'm', 'e', ' ', 'm', 'e', 'm', 'o', ' ', 'w', 'i', 't', 'h', ' ', 'b', 'o', 't', 't', 'o', 'm', ' ', 'f', 'r', 'a', 'm', 'e', ' ', '.', '.', '.', 0, 
	HB_P_PUSHBYTE, 30,	/* 30 */
	HB_P_PUSHBYTE, 30,	/* 30 */
	HB_P_PUSHINT, 44, 1,	/* 300 */
	HB_P_PUSHBYTE, 50,	/* 50 */
	HB_P_SENDSHORT, 5,
	HB_P_POPVARIABLE, 124, 0,	/* TMP_NAME */
/* 00113 */ HB_P_LINEOFFSET, 4,	/* 313 */
	HB_P_MESSAGE, 125, 0,	/* SETMANUALOBJPROPERTY */
	HB_P_PUSHVARIABLE, 5, 0,	/* FRPRN */
	HB_P_PUSHVARIABLE, 124, 0,	/* TMP_NAME */
	HB_P_PUSHSTRSHORT, 7,	/* 7 */
	'.', 'F', 'r', 'a', 'm', 'e', 0, 
	HB_P_PLUS,
	HB_P_PUSHSTRSHORT, 4,	/* 4 */
	'T', 'y', 'p', 0, 
	HB_P_PUSHSTRSHORT, 11,	/* 11 */
	'[', 'f', 't', 'B', 'o', 't', 't', 'o', 'm', ']', 0, 
	HB_P_SENDSHORT, 3,
	HB_P_POP,
/* 00156 */ HB_P_LINEOFFSET, 6,	/* 315 */
	HB_P_MESSAGE, 126, 0,	/* LINEAT */
	HB_P_PUSHVARIABLE, 5, 0,	/* FRPRN */
	HB_P_PUSHBYTE, 30,	/* 30 */
	HB_P_PUSHINT, 200, 0,	/* 200 */
	HB_P_PUSHBYTE, 100,	/* 100 */
	HB_P_PUSHBYTE, 100,	/* 100 */
	HB_P_SENDSHORT, 4,
	HB_P_POP,
/* 00176 */ HB_P_LINEOFFSET, 7,	/* 316 */
	HB_P_MESSAGE, 123, 0,	/* MEMOAT */
	HB_P_PUSHVARIABLE, 5, 0,	/* FRPRN */
	HB_P_PUSHSTRSHORT, 25,	/* 25 */
	'<', '-', '-', ' ', 'I', 't', 39, 's', ' ', 'a', ' ', 's', 'o', 'm', 'e', ' ', 'l', 'i', 'n', 'e', ' ', '.', '.', '.', 0, 
	HB_P_PUSHINT, 200, 0,	/* 200 */
	HB_P_PUSHINT, 250, 0,	/* 250 */
	HB_P_PUSHINT, 94, 1,	/* 350 */
	HB_P_PUSHBYTE, 50,	/* 50 */
	HB_P_SENDSHORT, 5,
	HB_P_POP,
/* 00225 */ HB_P_LINEOFFSET, 9,	/* 318 */
	HB_P_MESSAGE, 127, 0,	/* PICTUREAT */
	HB_P_PUSHVARIABLE, 5, 0,	/* FRPRN */
	HB_P_PUSHVARIABLE, 15, 0,	/* DATADIR */
	HB_P_PUSHSTRSHORT, 9,	/* 9 */
	'l', 'o', 'g', 'o', '.', 'b', 'm', 'p', 0, 
	HB_P_PLUS,
	HB_P_PUSHBYTE, 30,	/* 30 */
	HB_P_PUSHINT, 144, 1,	/* 400 */
	HB_P_PUSHINT, 44, 1,	/* 300 */
	HB_P_PUSHINT, 44, 1,	/* 300 */
	HB_P_SENDSHORT, 5,
	HB_P_POP,
/* 00262 */ HB_P_LINEOFFSET, 10,	/* 319 */
	HB_P_MESSAGE, 123, 0,	/* MEMOAT */
	HB_P_PUSHVARIABLE, 5, 0,	/* FRPRN */
	HB_P_PUSHSTRSHORT, 28,	/* 28 */
	'<', '-', '-', ' ', 'I', 't', 39, 's', ' ', 'a', ' ', 's', 'o', 'm', 'e', ' ', 'p', 'i', 'c', 't', 'u', 'r', 'e', ' ', '.', '.', '.', 0, 
	HB_P_PUSHINT, 94, 1,	/* 350 */
	HB_P_PUSHINT, 164, 1,	/* 420 */
	HB_P_PUSHINT, 64, 1,	/* 320 */
	HB_P_PUSHBYTE, 50,	/* 50 */
	HB_P_SENDSHORT, 5,
	HB_P_POP,
/* 00314 */ HB_P_LINEOFFSET, 12,	/* 321 */
	HB_P_MESSAGE, 128, 0,	/* NEWPAGE */
	HB_P_PUSHVARIABLE, 5, 0,	/* FRPRN */
	HB_P_SENDSHORT, 0,
	HB_P_POP,
/* 00325 */ HB_P_LINEOFFSET, 14,	/* 323 */
	HB_P_MESSAGE, 123, 0,	/* MEMOAT */
	HB_P_PUSHVARIABLE, 5, 0,	/* FRPRN */
	HB_P_PUSHSTRSHORT, 37,	/* 37 */
	'I', 't', 39, 's', ' ', 'a', ' ', 's', 'e', 'c', 'o', 'n', 'd', ' ', 'p', 'a', 'g', 'e', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', 0, 
	HB_P_PUSHBYTE, 30,	/* 30 */
	HB_P_PUSHBYTE, 30,	/* 30 */
	HB_P_PUSHBYTE, 100,	/* 100 */
	HB_P_PUSHINT, 232, 3,	/* 1000 */
	HB_P_SENDSHORT, 5,
	HB_P_POP,
/* 00384 */ HB_P_LINEOFFSET, 16,	/* 325 */
	HB_P_ENDPROC
/* 00387 */
   };

   hb_vmExecute( pcode, symbols );
}

HB_FUNC( DOMANUALREPORT )
{
   static const BYTE pcode[] =
   {
/* 00000 */ HB_P_BASELINE, 74, 1,	/* 330 */
	HB_P_MESSAGE, 129, 0,	/* STARTMANUALBUILD */
	HB_P_PUSHVARIABLE, 5, 0,	/* FRPRN */
	HB_P_PUSHBLOCKSHORT, 8,	/* 8 */
	HB_P_PUSHSYMNEAR, 121,	/* MYMANUALREPORT */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_ENDBLOCK,
	HB_P_ONE,
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 3,	/* 3 */
	HB_P_SENDSHORT, 4,
	HB_P_POP,
/* 00024 */ HB_P_LINEOFFSET, 1,	/* 331 */
	HB_P_PUSHSYMNEAR, 90,	/* DOFRACTION */
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 0,
/* 00031 */ HB_P_LINEOFFSET, 3,	/* 333 */
	HB_P_ENDPROC
/* 00034 */
   };

   hb_vmExecute( pcode, symbols );
}

HB_FUNC( DOMEMPICT )
{
   static const BYTE pcode[] =
   {
/* 00000 */ HB_P_BASELINE, 82, 1,	/* 338 */
	HB_P_PUSHSYMNEAR, 19,	/* DBUSEAREA */
	HB_P_PUSHNIL,
	HB_P_TRUE,
	HB_P_PUSHSTRSHORT, 7,	/* 7 */
	'D', 'B', 'F', 'C', 'D', 'X', 0, 
	HB_P_PUSHVARIABLE, 15, 0,	/* DATADIR */
	HB_P_PUSHSTRSHORT, 12,	/* 12 */
	'B', 'i', 'o', 'l', 'i', 'f', 'e', '.', 'd', 'b', 'f', 0, 
	HB_P_PLUS,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_FALSE,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 8,
/* 00041 */ HB_P_LINEOFFSET, 1,	/* 339 */
	HB_P_PUSHSYMNEAR, 31,	/* DBGOTOP */
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 0,
/* 00048 */ HB_P_LINEOFFSET, 3,	/* 341 */
	HB_P_MESSAGE, 111, 0,	/* SETWORKAREA */
	HB_P_PUSHVARIABLE, 5, 0,	/* FRPRN */
	HB_P_PUSHSTRSHORT, 8,	/* 8 */
	'B', 'i', 'o', 'l', 'i', 'f', 'e', 0, 
	HB_P_PUSHBYTE, 5,	/* 5 */
	HB_P_SENDSHORT, 2,
	HB_P_POP,
/* 00071 */ HB_P_LINEOFFSET, 4,	/* 342 */
	HB_P_PUSHSYMNEAR, 90,	/* DOFRACTION */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 9,	/* 9 */
	'9', 'n', 'e', 'w', '.', 'f', 'r', '3', 0, 
	HB_P_DOSHORT, 1,
/* 00089 */ HB_P_LINEOFFSET, 6,	/* 344 */
	HB_P_PUSHALIAS,
	HB_P_PUSHSYMNEAR, 130,	/* BIOLIFE */
	HB_P_POPALIAS,
	HB_P_PUSHSYMNEAR, 23,	/* DBCLOSEAREA */
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 0,
	HB_P_POPALIAS,
/* 00101 */ HB_P_LINEOFFSET, 8,	/* 346 */
	HB_P_ENDPROC
/* 00104 */
   };

   hb_vmExecute( pcode, symbols );
}

HB_FUNC( DOUSERDS )
{
   static const BYTE pcode[] =
   {
/* 00000 */ HB_P_BASELINE, 95, 1,	/* 351 */
	HB_P_ONE,
	HB_P_PUSHSTRSHORT, 7,	/* 7 */
	'C', ':', 92, '*', '.', '*', 0, 
	HB_P_PUSHSYMNEAR, 8,	/* __MVPRIVATE */
	HB_P_PUSHNIL,
	HB_P_PUSHSYMNEAR, 131,	/* ADIR */
	HB_P_PUSHSYMNEAR, 132,	/* I */
	HB_P_PUSHSYMNEAR, 133,	/* DIRNAME */
	HB_P_DOSHORT, 3,
	HB_P_POPVARIABLE, 133, 0,	/* DIRNAME */
	HB_P_POPVARIABLE, 132, 0,	/* I */
/* 00030 */ HB_P_LINEOFFSET, 2,	/* 353 */
	HB_P_PUSHSYMNEAR, 81,	/* DIRECTORY */
	HB_P_PUSHNIL,
	HB_P_PUSHVARIABLE, 133, 0,	/* DIRNAME */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_POPVARIABLE, 131, 0,	/* ADIR */
/* 00043 */ HB_P_LINEOFFSET, 6,	/* 357 */
	HB_P_MESSAGE, 134, 0,	/* SETUSERDATASET */
	HB_P_PUSHVARIABLE, 5, 0,	/* FRPRN */
	HB_P_PUSHSTRSHORT, 4,	/* 4 */
	'D', 'i', 'r', 0, 
	HB_P_PUSHSTRSHORT, 30,	/* 30 */
	'F', '_', 'N', 'A', 'M', 'E', ';', 'F', '_', 'S', 'I', 'Z', 'E', ';', 'F', '_', 'C', 'R', 'E', 'A', 'T', 'I', 'O', 'N', '_', 'D', 'A', 'T', 'E', 0, 
	HB_P_PUSHBLOCKSHORT, 8,	/* 8 */
	HB_P_ONE,
	HB_P_DUPLICATE,
	HB_P_POPVARIABLE, 132, 0,	/* I */
	HB_P_ENDBLOCK,
	HB_P_PUSHBLOCKSHORT, 13,	/* 13 */
	HB_P_PUSHVARIABLE, 132, 0,	/* I */
	HB_P_ADDINT, 1, 0,	/* 1*/
	HB_P_DUPLICATE,
	HB_P_POPVARIABLE, 132, 0,	/* I */
	HB_P_ENDBLOCK,
	HB_P_PUSHBLOCKSHORT, 13,	/* 13 */
	HB_P_PUSHVARIABLE, 132, 0,	/* I */
	HB_P_ADDINT, 255, 255,	/* -1*/
	HB_P_DUPLICATE,
	HB_P_POPVARIABLE, 132, 0,	/* I */
	HB_P_ENDBLOCK,
	HB_P_PUSHBLOCKSHORT, 15,	/* 15 */
	HB_P_PUSHVARIABLE, 132, 0,	/* I */
	HB_P_PUSHSYMNEAR, 84,	/* LEN */
	HB_P_PUSHNIL,
	HB_P_PUSHVARIABLE, 131, 0,	/* ADIR */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_GREATER,
	HB_P_ENDBLOCK,
	HB_P_PUSHBLOCK, 59, 0,	/* 59 */
	1, 0,	/* number of local parameters (1) */
	0, 0,	/* number of local variables (0) */
	HB_P_PUSHLOCALNEAR, 1,	/* codeblockvar1 */
	HB_P_PUSHSTRSHORT, 7,	/* 7 */
	'F', '_', 'N', 'A', 'M', 'E', 0, 
	HB_P_EQUAL,
	HB_P_JUMPFALSENEAR, 5,	/* 5 (abs: 00162) */
	HB_P_ONE,
	HB_P_JUMPNEAR, 22,	/* 22 (abs: 00182) */
	HB_P_PUSHLOCALNEAR, 1,	/* codeblockvar1 */
	HB_P_PUSHSTRSHORT, 7,	/* 7 */
	'F', '_', 'S', 'I', 'Z', 'E', 0, 
	HB_P_EQUAL,
	HB_P_JUMPFALSENEAR, 6,	/* 6 (abs: 00180) */
	HB_P_PUSHBYTE, 2,	/* 2 */
	HB_P_JUMPNEAR, 4,	/* 4 (abs: 00182) */
	HB_P_PUSHBYTE, 3,	/* 3 */
	HB_P_POPVARIABLE, 135, 0,	/* XX */
	HB_P_PUSHMEMVAR, 131, 0,	/* ADIR */
	HB_P_PUSHVARIABLE, 132, 0,	/* I */
	HB_P_ARRAYPUSH,
	HB_P_PUSHVARIABLE, 135, 0,	/* XX */
	HB_P_ARRAYPUSH,
	HB_P_ENDBLOCK,
	HB_P_SENDSHORT, 7,
	HB_P_POP,
/* 00200 */ HB_P_LINEOFFSET, 8,	/* 359 */
	HB_P_PUSHSYMNEAR, 90,	/* DOFRACTION */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 6,	/* 6 */
	'6', '.', 'f', 'r', '3', 0, 
	HB_P_DOSHORT, 1,
/* 00215 */ HB_P_LINEOFFSET, 9,	/* 360 */
	HB_P_MESSAGE, 113, 0,	/* CLEARDATASETS */
	HB_P_PUSHVARIABLE, 5, 0,	/* FRPRN */
	HB_P_SENDSHORT, 0,
	HB_P_POP,
/* 00226 */ HB_P_LINEOFFSET, 11,	/* 362 */
	HB_P_ENDPROC
/* 00229 */
   };

   hb_vmExecute( pcode, symbols );
}

HB_FUNC( GETDSVALUE )
{
   static const BYTE pcode[] =
   {
	HB_P_FRAME, 1, 1,	/* locals, params */
/* 00003 */ HB_P_BASELINE, 114, 1,	/* 370 */
	HB_P_PUSHLOCALNEAR, 1,	/* CFIELD */
	HB_P_PUSHSTRSHORT, 7,	/* 7 */
	'P', 'a', 'r', 't', 'N', 'o', 0, 
	HB_P_EXACTLYEQUAL,
	HB_P_JUMPFALSENEAR, 10,	/* 10 (abs: 00028) */
/* 00020 */ HB_P_LINEOFFSET, 1,	/* 371 */
	HB_P_PUSHSYMNEAR, 137,	/* PARTS */
	HB_P_PUSHALIASEDFIELDNEAR, 27,	/* PARTNO */
	HB_P_RETVALUE,
	HB_P_ENDPROC,
/* 00028 */ HB_P_LINEOFFSET, 2,	/* 372 */
	HB_P_PUSHLOCALNEAR, 1,	/* CFIELD */
	HB_P_PUSHSTRSHORT, 5,	/* 5 */
	'P', 'a', 'r', 't', 0, 
	HB_P_EXACTLYEQUAL,
	HB_P_JUMPFALSENEAR, 10,	/* 10 (abs: 00050) */
/* 00042 */ HB_P_LINEOFFSET, 3,	/* 373 */
	HB_P_PUSHSYMNEAR, 137,	/* PARTS */
	HB_P_PUSHALIASEDFIELDNEAR, 138,	/* DESCRIPTIO */
	HB_P_RETVALUE,
	HB_P_ENDPROC,
/* 00050 */ HB_P_LINEOFFSET, 4,	/* 374 */
	HB_P_PUSHLOCALNEAR, 1,	/* CFIELD */
	HB_P_PUSHSTRSHORT, 10,	/* 10 */
	'T', 'o', 't', 'a', 'l', ' ', 'q', 't', 'y', 0, 
	HB_P_EXACTLYEQUAL,
	HB_P_JUMPFALSENEAR, 80,	/* 80 (abs: 00147) */
/* 00069 */ HB_P_LINEOFFSET, 5,	/* 375 */
	HB_P_PUSHSYMNEAR, 114,	/* DBSELECTAREA */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 6,	/* 6 */
	'I', 't', 'e', 'm', 's', 0, 
	HB_P_DOSHORT, 1,
/* 00084 */ HB_P_LINEOFFSET, 6,	/* 376 */
	HB_P_PUSHSYMNEAR, 139,	/* ORDSCOPE */
	HB_P_PUSHNIL,
	HB_P_ZERO,
	HB_P_PUSHSYMNEAR, 137,	/* PARTS */
	HB_P_PUSHALIASEDFIELDNEAR, 27,	/* PARTNO */
	HB_P_DOSHORT, 2,
/* 00096 */ HB_P_LINEOFFSET, 7,	/* 377 */
	HB_P_PUSHSYMNEAR, 139,	/* ORDSCOPE */
	HB_P_PUSHNIL,
	HB_P_ONE,
	HB_P_PUSHSYMNEAR, 137,	/* PARTS */
	HB_P_PUSHALIASEDFIELDNEAR, 27,	/* PARTNO */
	HB_P_DOSHORT, 2,
/* 00108 */ HB_P_LINEOFFSET, 8,	/* 378 */
	HB_P_LOCALNEARSETINT, 2, 0, 0,	/* RES 0*/
	HB_P_PUSHSYMNEAR, 140,	/* DBEVAL */
	HB_P_PUSHNIL,
	HB_P_PUSHBLOCK, 17, 0,	/* 17 */
	0, 0,	/* number of local parameters (0) */
	1, 0,	/* number of local variables (1) */
	2, 0,	/* RES */
	HB_P_PUSHVARIABLE, 141, 0,	/* QTY */
	HB_P_LOCALNEARADD, 255,	/* localvar1 */
	HB_P_PUSHLOCALNEAR, 255,	/* localvar1 */
	HB_P_ENDBLOCK,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_FALSE,
	HB_P_DOSHORT, 6,
/* 00141 */ HB_P_LINEOFFSET, 9,	/* 379 */
	HB_P_PUSHLOCALNEAR, 2,	/* RES */
	HB_P_RETVALUE,
	HB_P_ENDPROC,
/* 00147 */ HB_P_LINEOFFSET, 10,	/* 380 */
	HB_P_PUSHLOCALNEAR, 1,	/* CFIELD */
	HB_P_PUSHSTRSHORT, 6,	/* 6 */
	'P', 'r', 'i', 'c', 'e', 0, 
	HB_P_EXACTLYEQUAL,
	HB_P_JUMPFALSENEAR, 10,	/* 10 (abs: 00170) */
/* 00162 */ HB_P_LINEOFFSET, 11,	/* 381 */
	HB_P_PUSHSYMNEAR, 137,	/* PARTS */
	HB_P_PUSHALIASEDFIELDNEAR, 142,	/* LISTPRICE */
	HB_P_RETVALUE,
	HB_P_ENDPROC,
/* 00170 */ HB_P_LINEOFFSET, 14,	/* 384 */
	HB_P_PUSHNIL,
	HB_P_RETVALUE,
	HB_P_ENDPROC
/* 00175 */
   };

   hb_vmExecute( pcode, symbols );
}

HB_FUNC( DOWAUSERDS )
{
   static const BYTE pcode[] =
   {
/* 00000 */ HB_P_BASELINE, 133, 1,	/* 389 */
	HB_P_PUSHSYMNEAR, 114,	/* DBSELECTAREA */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 6,	/* 6 */
	'I', 't', 'e', 'm', 's', 0, 
	HB_P_DOSHORT, 1,
/* 00016 */ HB_P_LINEOFFSET, 1,	/* 390 */
	HB_P_PUSHSYMNEAR, 30,	/* ORDSETFOCUS */
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 3,	/* 3 */
	HB_P_DOSHORT, 1,
/* 00025 */ HB_P_LINEOFFSET, 7,	/* 396 */
	HB_P_MESSAGE, 134, 0,	/* SETUSERDATASET */
	HB_P_PUSHVARIABLE, 5, 0,	/* FRPRN */
	HB_P_PUSHSTRSHORT, 15,	/* 15 */
	'P', 'a', 'r', 't', 's', ' ', 'i', 'n', ' ', 'o', 'd', 'e', 'r', 's', 0, 
	HB_P_PUSHSTRSHORT, 28,	/* 28 */
	'P', 'a', 'r', 't', 'N', 'o', ';', 'P', 'a', 'r', 't', ';', 'T', 'o', 't', 'a', 'l', ' ', 'q', 't', 'y', ';', 'P', 'r', 'i', 'c', 'e', 0, 
	HB_P_PUSHBLOCKSHORT, 13,	/* 13 */
	HB_P_PUSHALIAS,
	HB_P_PUSHSYMNEAR, 137,	/* PARTS */
	HB_P_POPALIAS,
	HB_P_PUSHSYMNEAR, 31,	/* DBGOTOP */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_SWAPALIAS,
	HB_P_ENDBLOCK,
	HB_P_PUSHBLOCKSHORT, 14,	/* 14 */
	HB_P_PUSHALIAS,
	HB_P_PUSHSYMNEAR, 137,	/* PARTS */
	HB_P_POPALIAS,
	HB_P_PUSHSYMNEAR, 143,	/* DBSKIP */
	HB_P_PUSHNIL,
	HB_P_ONE,
	HB_P_FUNCTIONSHORT, 1,
	HB_P_SWAPALIAS,
	HB_P_ENDBLOCK,
	HB_P_PUSHBLOCKSHORT, 15,	/* 15 */
	HB_P_PUSHALIAS,
	HB_P_PUSHSYMNEAR, 137,	/* PARTS */
	HB_P_POPALIAS,
	HB_P_PUSHSYMNEAR, 143,	/* DBSKIP */
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 255,	/* -1 */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_SWAPALIAS,
	HB_P_ENDBLOCK,
	HB_P_PUSHBLOCKSHORT, 13,	/* 13 */
	HB_P_PUSHALIAS,
	HB_P_PUSHSYMNEAR, 137,	/* PARTS */
	HB_P_POPALIAS,
	HB_P_PUSHSYMNEAR, 144,	/* EOF */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_SWAPALIAS,
	HB_P_ENDBLOCK,
	HB_P_PUSHBLOCK, 15, 0,	/* 15 */
	1, 0,	/* number of local parameters (1) */
	0, 0,	/* number of local variables (0) */
	HB_P_PUSHSYMNEAR, 136,	/* GETDSVALUE */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 1,	/* codeblockvar1 */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_ENDBLOCK,
	HB_P_SENDSHORT, 7,
	HB_P_POP,
/* 00153 */ HB_P_LINEOFFSET, 9,	/* 398 */
	HB_P_PUSHSYMNEAR, 90,	/* DOFRACTION */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 6,	/* 6 */
	'9', '.', 'f', 'r', '3', 0, 
	HB_P_DOSHORT, 1,
/* 00168 */ HB_P_LINEOFFSET, 10,	/* 399 */
	HB_P_PUSHSYMNEAR, 114,	/* DBSELECTAREA */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 6,	/* 6 */
	'I', 't', 'e', 'm', 's', 0, 
	HB_P_DOSHORT, 1,
/* 00183 */ HB_P_LINEOFFSET, 11,	/* 400 */
	HB_P_PUSHSYMNEAR, 139,	/* ORDSCOPE */
	HB_P_PUSHNIL,
	HB_P_ZERO,
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 2,
/* 00192 */ HB_P_LINEOFFSET, 12,	/* 401 */
	HB_P_PUSHSYMNEAR, 139,	/* ORDSCOPE */
	HB_P_PUSHNIL,
	HB_P_ONE,
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 2,
/* 00201 */ HB_P_LINEOFFSET, 13,	/* 402 */
	HB_P_MESSAGE, 113, 0,	/* CLEARDATASETS */
	HB_P_PUSHVARIABLE, 5, 0,	/* FRPRN */
	HB_P_SENDSHORT, 0,
	HB_P_POP,
/* 00212 */ HB_P_LINEOFFSET, 15,	/* 404 */
	HB_P_ENDPROC
/* 00215 */
   };

   hb_vmExecute( pcode, symbols );
}

HB_FUNC( DOADO )
{
   static const BYTE pcode[] =
   {
/* 00000 */ HB_P_BASELINE, 153, 1,	/* 409 */
	HB_P_MESSAGE, 96, 0,	/* LOADFROMFILE */
	HB_P_PUSHVARIABLE, 5, 0,	/* FRPRN */
	HB_P_PUSHVARIABLE, 14, 0,	/* REPDIR */
	HB_P_PUSHSTRSHORT, 7,	/* 7 */
	'2', '4', '.', 'f', 'r', '3', 0, 
	HB_P_PLUS,
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00025 */ HB_P_LINEOFFSET, 1,	/* 410 */
	HB_P_MESSAGE, 145, 0,	/* SETADOCONNECTPARTSTR */
	HB_P_PUSHVARIABLE, 5, 0,	/* FRPRN */
	HB_P_PUSHSTRSHORT, 13,	/* 13 */
	'A', 'D', 'O', 'D', 'a', 't', 'a', 'b', 'a', 's', 'e', '1', 0, 
	HB_P_PUSHSTRSHORT, 12,	/* 12 */
	'D', 'a', 't', 'a', ' ', 'S', 'o', 'u', 'r', 'c', 'e', 0, 
	HB_P_PUSHVARIABLE, 15, 0,	/* DATADIR */
	HB_P_PUSHSTRSHORT, 9,	/* 9 */
	'd', 'e', 'm', 'o', '.', 'm', 'd', 'b', 0, 
	HB_P_PLUS,
	HB_P_SENDSHORT, 3,
	HB_P_POP,
/* 00080 */ HB_P_LINEOFFSET, 2,	/* 411 */
	HB_P_PUSHSYMNEAR, 90,	/* DOFRACTION */
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 0,
/* 00087 */ HB_P_LINEOFFSET, 4,	/* 413 */
	HB_P_ENDPROC
/* 00090 */
   };

   hb_vmExecute( pcode, symbols );
}

HB_FUNC( DOSOMECALLS )
{
   static const BYTE pcode[] =
   {
/* 00000 */ HB_P_BASELINE, 162, 1,	/* 418 */
	HB_P_MESSAGE, 96, 0,	/* LOADFROMFILE */
	HB_P_PUSHVARIABLE, 5, 0,	/* FRPRN */
	HB_P_PUSHVARIABLE, 14, 0,	/* REPDIR */
	HB_P_PUSHSTRSHORT, 6,	/* 6 */
	'7', '.', 'f', 'r', '3', 0, 
	HB_P_PLUS,
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00024 */ HB_P_LINEOFFSET, 1,	/* 419 */
	HB_P_MESSAGE, 146, 0,	/* ADDVARIABLE */
	HB_P_PUSHVARIABLE, 5, 0,	/* FRPRN */
	HB_P_PUSHSTRSHORT, 15,	/* 15 */
	'M', 'y', ' ', 'L', 'o', 'v', 'e', 'l', 'y', ' ', 'V', 'a', 'r', 's', 0, 
	HB_P_PUSHSTRSHORT, 19,	/* 19 */
	'M', 'y', ' ', 'a', 'n', 'd', ' ', 'o', 'n', 'l', 'y', ' ', 'm', 'y', ' ', 'v', 'a', 'r', 0, 
	HB_P_PUSHBYTE, 10,	/* 10 */
	HB_P_SENDSHORT, 3,
	HB_P_POP,
/* 00075 */ HB_P_LINEOFFSET, 2,	/* 420 */
	HB_P_MESSAGE, 146, 0,	/* ADDVARIABLE */
	HB_P_PUSHVARIABLE, 5, 0,	/* FRPRN */
	HB_P_PUSHSTRSHORT, 15,	/* 15 */
	'M', 'y', ' ', 'L', 'o', 'v', 'e', 'l', 'y', ' ', 'V', 'a', 'r', 's', 0, 
	HB_P_PUSHSTRSHORT, 5,	/* 5 */
	't', 'e', 's', 't', 0, 
	HB_P_PUSHDOUBLE, 0, 0, 0, 0, 0, 16, 89, 64, 10, 2,	/* 100.25, 10, 2 */
	HB_P_SENDSHORT, 3,
	HB_P_POP,
/* 00121 */ HB_P_LINEOFFSET, 3,	/* 421 */
	HB_P_MESSAGE, 146, 0,	/* ADDVARIABLE */
	HB_P_PUSHVARIABLE, 5, 0,	/* FRPRN */
	HB_P_PUSHSTRSHORT, 15,	/* 15 */
	'M', 'y', ' ', 'L', 'o', 'v', 'e', 'l', 'y', ' ', 'V', 'a', 'r', 's', 0, 
	HB_P_PUSHSTRSHORT, 6,	/* 6 */
	't', 'e', 's', 't', '1', 0, 
	HB_P_PUSHSTRSHORT, 7,	/* 7 */
	39, 'T', 'e', 's', 't', 39, 0, 
	HB_P_SENDSHORT, 3,
	HB_P_POP,
/* 00166 */ HB_P_LINEOFFSET, 4,	/* 422 */
	HB_P_MESSAGE, 146, 0,	/* ADDVARIABLE */
	HB_P_PUSHVARIABLE, 5, 0,	/* FRPRN */
	HB_P_PUSHSTRSHORT, 15,	/* 15 */
	'M', 'y', ' ', 'L', 'o', 'v', 'e', 'l', 'y', ' ', 'V', 'a', 'r', 's', 0, 
	HB_P_PUSHSTRSHORT, 6,	/* 6 */
	't', 'e', 's', 't', '2', 0, 
	HB_P_PUSHSYMNEAR, 147,	/* CTOD */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 11,	/* 11 */
	'0', '1', '/', '0', '1', '/', '2', '0', '0', '7', 0, 
	HB_P_FUNCTIONSHORT, 1,
	HB_P_SENDSHORT, 3,
	HB_P_POP,
/* 00220 */ HB_P_LINEOFFSET, 5,	/* 423 */
	HB_P_PUSHSYMNEAR, 90,	/* DOFRACTION */
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 0,
/* 00227 */ HB_P_LINEOFFSET, 7,	/* 425 */
	HB_P_ENDPROC
/* 00230 */
   };

   hb_vmExecute( pcode, symbols );
}

HB_FUNC( GETEXPORTOBJECT )
{
   static const BYTE pcode[] =
   {
	HB_P_FRAME, 7, 0,	/* locals, params */
/* 00003 */ HB_P_BASELINE, 177, 1,	/* 433 */
	HB_P_PUSHSTRSHORT, 10,	/* 10 */
	'P', 'D', 'F', 'E', 'x', 'p', 'o', 'r', 't', 0, 
	HB_P_PUSHSTRSHORT, 11,	/* 11 */
	'H', 'T', 'M', 'L', 'E', 'x', 'p', 'o', 'r', 't', 0, 
	HB_P_PUSHSTRSHORT, 10,	/* 10 */
	'R', 'T', 'F', 'E', 'x', 'p', 'o', 'r', 't', 0, 
	HB_P_PUSHSTRSHORT, 10,	/* 10 */
	'C', 'S', 'V', 'E', 'x', 'p', 'o', 'r', 't', 0, 
	HB_P_PUSHSTRSHORT, 10,	/* 10 */
	'X', 'L', 'S', 'E', 'x', 'p', 'o', 'r', 't', 0, 
	HB_P_PUSHSTRSHORT, 16,	/* 16 */
	'D', 'o', 't', 'M', 'a', 't', 'r', 'i', 'x', 'E', 'x', 'p', 'o', 'r', 't', 0, 
	HB_P_PUSHSTRSHORT, 10,	/* 10 */
	'B', 'M', 'P', 'E', 'x', 'p', 'o', 'r', 't', 0, 
	HB_P_PUSHSTRSHORT, 11,	/* 11 */
	'J', 'P', 'E', 'G', 'E', 'x', 'p', 'o', 'r', 't', 0, 
	HB_P_PUSHSTRSHORT, 10,	/* 10 */
	'T', 'X', 'T', 'E', 'x', 'p', 'o', 'r', 't', 0, 
	HB_P_PUSHSTRSHORT, 11,	/* 11 */
	'T', 'I', 'F', 'F', 'E', 'x', 'p', 'o', 'r', 't', 0, 
	HB_P_PUSHSTRSHORT, 10,	/* 10 */
	'G', 'I', 'F', 'E', 'x', 'p', 'o', 'r', 't', 0, 
	HB_P_PUSHSTRSHORT, 17,	/* 17 */
	'S', 'i', 'm', 'p', 'l', 'e', 'T', 'e', 'x', 't', 'E', 'x', 'p', 'o', 'r', 't', 0, 
	HB_P_PUSHSTRSHORT, 11,	/* 11 */
	'M', 'a', 'i', 'l', 'E', 'x', 'p', 'o', 'r', 't', 0, 
	HB_P_PUSHSTRSHORT, 10,	/* 10 */
	'X', 'M', 'L', 'E', 'x', 'p', 'o', 'r', 't', 0, 
	HB_P_ARRAYGEN, 14, 0,	/* 14 */
	HB_P_POPLOCALNEAR, 1,	/* AEXPLIST */
/* 00196 */ HB_P_LINEOFFSET, 1,	/* 434 */
	HB_P_ARRAYGEN, 0, 0,	/* 0 */
	HB_P_POPLOCALNEAR, 2,	/* ADADOS */
	HB_P_ARRAYGEN, 0, 0,	/* 0 */
	HB_P_POPLOCALNEAR, 3,	/* AOGETS */
	HB_P_ARRAYGEN, 0, 0,	/* 0 */
	HB_P_POPLOCALNEAR, 4,	/* ATIPOSEXP */
	HB_P_FALSE,
	HB_P_POPLOCALNEAR, 5,	/* LEXPORT */
/* 00216 */ HB_P_LINEOFFSET, 4,	/* 437 */
	HB_P_ONE,
	HB_P_POPVARIABLE, 83, 0,	/* X */
	HB_P_PUSHVARIABLE, 83, 0,	/* X */
	HB_P_PUSHSYMNEAR, 84,	/* LEN */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 1,	/* AEXPLIST */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_LESSEQUAL,
	HB_P_JUMPFALSENEAR, 31,	/* 31 (abs: 00264) */
/* 00235 */ HB_P_LINEOFFSET, 5,	/* 438 */
	HB_P_PUSHSYMNEAR, 85,	/* AADD */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 4,	/* ATIPOSEXP */
	HB_P_PUSHLOCALNEAR, 1,	/* AEXPLIST */
	HB_P_PUSHVARIABLE, 83, 0,	/* X */
	HB_P_ARRAYPUSH,
	HB_P_ARRAYGEN, 1, 0,	/* 1 */
	HB_P_DOSHORT, 2,
/* 00253 */ HB_P_LINEOFFSET, 6,	/* 439 */
	HB_P_PUSHVARIABLE, 83, 0,	/* X */
	HB_P_INC,
	HB_P_POPVARIABLE, 83, 0,	/* X */
	HB_P_JUMPNEAR, 216,	/* -40 (abs: 00222) */
/* 00264 */ HB_P_LINEOFFSET, 7,	/* 440 */
	HB_P_PUSHSYMNEAR, 85,	/* AADD */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 2,	/* ADADOS */
	HB_P_PUSHVARIABLE, 14, 0,	/* REPDIR */
	HB_P_PUSHSTRSHORT, 7,	/* 7 */
	'e', 'x', 'p', 'o', 'r', 't', 0, 
	HB_P_PLUS,
	HB_P_DOSHORT, 2,
/* 00286 */ HB_P_LINEOFFSET, 8,	/* 441 */
	HB_P_PUSHSYMNEAR, 85,	/* AADD */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 2,	/* ADADOS */
	HB_P_TRUE,
	HB_P_DOSHORT, 2,
/* 00296 */ HB_P_LINEOFFSET, 9,	/* 442 */
	HB_P_PUSHSYMNEAR, 85,	/* AADD */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 2,	/* ADADOS */
	HB_P_TRUE,
	HB_P_DOSHORT, 2,
/* 00306 */ HB_P_LINEOFFSET, 10,	/* 443 */
	HB_P_PUSHSYMNEAR, 148,	/* ARRAY */
	HB_P_PUSHNIL,
	HB_P_PUSHSYMNEAR, 84,	/* LEN */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 2,	/* ADADOS */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_FUNCTIONSHORT, 1,
	HB_P_POPLOCALNEAR, 3,	/* AOGETS */
/* 00322 */ HB_P_LINEOFFSET, 12,	/* 445 */
	HB_P_MESSAGE, 10, 0,	/* NEW */
	HB_P_PUSHSYMNEAR, 32,	/* TDIALOG */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 8,	/* 8 */
	'E', 'X', 'P', 'O', 'R', 'T', 'A', 0, 
	HB_P_PUSHNIL,
	HB_P_FALSE,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_FALSE,
	HB_P_PUSHSTRSHORT, 5,	/* 5 */
	'D', 'E', 'M', 'O', 0, 
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_FALSE,
	HB_P_SENDSHORT, 20,
	HB_P_POPLOCALNEAR, 7,	/* ODLG */
/* 00371 */ HB_P_LINEOFFSET, 13,	/* 446 */
	HB_P_MESSAGE, 33, 0,	/* _LHELPICON */
	HB_P_PUSHLOCALNEAR, 7,	/* ODLG */
	HB_P_FALSE,
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00382 */ HB_P_LINEOFFSET, 19,	/* 452 */
	HB_P_MESSAGE, 40, 0,	/* REDEFINE */
	HB_P_PUSHSYMNEAR, 149,	/* TWBROWSE */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_PUSHINT, 77, 4,	/* 1101 */
	HB_P_PUSHBLOCK, 27, 0,	/* 27 */
	0, 0,	/* number of local parameters (0) */
	2, 0,	/* number of local variables (2) */
	4, 0,	/* ATIPOSEXP */
	6, 0,	/* OLBX */
	HB_P_PUSHLOCALNEAR, 255,	/* localvar1 */
	HB_P_MESSAGE, 150, 0,	/* NAT */
	HB_P_PUSHLOCALNEAR, 254,	/* localvar2 */
	HB_P_SENDSHORT, 0,
	HB_P_ARRAYPUSH,
	HB_P_ONE,
	HB_P_ARRAYPUSH,
	HB_P_ARRAYGEN, 1, 0,	/* 1 */
	HB_P_ENDBLOCK,
	HB_P_PUSHLOCALNEAR, 7,	/* ODLG */
	HB_P_PUSHSTRSHORT, 13,	/* 13 */
	'E', 'x', 'p', 'o', 'r', 't', ' ', 't', 'y', 'p', 'e', 's', 0, 
	HB_P_ARRAYGEN, 1, 0,	/* 1 */
	HB_P_PUSHINT, 250, 0,	/* 250 */
	HB_P_ARRAYGEN, 1, 0,	/* 1 */
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHLONG, 0, 0, 128, 0, 	/* 8388608 */
	HB_P_PUSHLONG, 255, 255, 255, 0, 	/* 16777215 */
	HB_P_PUSHNIL,
	HB_P_FALSE,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_SENDSHORT, 22,
	HB_P_POPLOCALNEAR, 6,	/* OLBX */
/* 00477 */ HB_P_LINEOFFSET, 20,	/* 453 */
	HB_P_MESSAGE, 151, 0,	/* SETARRAY */
	HB_P_PUSHLOCALNEAR, 6,	/* OLBX */
	HB_P_PUSHLOCALNEAR, 4,	/* ATIPOSEXP */
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00489 */ HB_P_LINEOFFSET, 22,	/* 455 */
	HB_P_MESSAGE, 40, 0,	/* REDEFINE */
	HB_P_PUSHSYMNEAR, 152,	/* TGET */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_PUSHBYTE, 101,	/* 101 */
	HB_P_PUSHBLOCK, 33, 0,	/* 33 */
	1, 0,	/* number of local parameters (1) */
	1, 0,	/* number of local variables (1) */
	2, 0,	/* ADADOS */
	HB_P_PUSHSYMNEAR, 42,	/* PCOUNT */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_ZERO,
	HB_P_EXACTLYEQUAL,
	HB_P_JUMPFALSENEAR, 8,	/* 8 (abs: 00525) */
	HB_P_PUSHLOCALNEAR, 255,	/* localvar1 */
	HB_P_ONE,
	HB_P_ARRAYPUSH,
	HB_P_JUMPNEAR, 10,	/* 10 (abs: 00533) */
	HB_P_PUSHLOCALNEAR, 1,	/* codeblockvar1 */
	HB_P_DUPLICATE,
	HB_P_PUSHLOCALREF, 255, 255,	/* localvar1 */
	HB_P_ONE,
	HB_P_ARRAYPOP,
	HB_P_ENDBLOCK,
	HB_P_PUSHLOCALNEAR, 7,	/* ODLG */
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_TRUE,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_FALSE,
	HB_P_FALSE,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_SENDSHORT, 20,
	HB_P_PUSHLOCALREF, 3, 0,	/* AOGETS */
	HB_P_ONE,
	HB_P_ARRAYPOP,
/* 00560 */ HB_P_LINEOFFSET, 23,	/* 456 */
	HB_P_MESSAGE, 40, 0,	/* REDEFINE */
	HB_P_PUSHSYMNEAR, 153,	/* TCHECKBOX */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_PUSHBYTE, 102,	/* 102 */
	HB_P_PUSHBLOCK, 35, 0,	/* 35 */
	1, 0,	/* number of local parameters (1) */
	1, 0,	/* number of local variables (1) */
	2, 0,	/* ADADOS */
	HB_P_PUSHSYMNEAR, 42,	/* PCOUNT */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_ZERO,
	HB_P_EXACTLYEQUAL,
	HB_P_JUMPFALSENEAR, 9,	/* 9 (abs: 00597) */
	HB_P_PUSHLOCALNEAR, 255,	/* localvar1 */
	HB_P_PUSHBYTE, 2,	/* 2 */
	HB_P_ARRAYPUSH,
	HB_P_JUMPNEAR, 11,	/* 11 (abs: 00606) */
	HB_P_PUSHLOCALNEAR, 1,	/* codeblockvar1 */
	HB_P_DUPLICATE,
	HB_P_PUSHLOCALREF, 255, 255,	/* localvar1 */
	HB_P_PUSHBYTE, 2,	/* 2 */
	HB_P_ARRAYPOP,
	HB_P_ENDBLOCK,
	HB_P_PUSHLOCALNEAR, 7,	/* ODLG */
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_FALSE,
	HB_P_PUSHNIL,
	HB_P_SENDSHORT, 11,
	HB_P_PUSHLOCALREF, 3, 0,	/* AOGETS */
	HB_P_PUSHBYTE, 2,	/* 2 */
	HB_P_ARRAYPOP,
/* 00625 */ HB_P_LINEOFFSET, 24,	/* 457 */
	HB_P_MESSAGE, 40, 0,	/* REDEFINE */
	HB_P_PUSHSYMNEAR, 153,	/* TCHECKBOX */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_PUSHBYTE, 103,	/* 103 */
	HB_P_PUSHBLOCK, 35, 0,	/* 35 */
	1, 0,	/* number of local parameters (1) */
	1, 0,	/* number of local variables (1) */
	2, 0,	/* ADADOS */
	HB_P_PUSHSYMNEAR, 42,	/* PCOUNT */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_ZERO,
	HB_P_EXACTLYEQUAL,
	HB_P_JUMPFALSENEAR, 9,	/* 9 (abs: 00662) */
	HB_P_PUSHLOCALNEAR, 255,	/* localvar1 */
	HB_P_PUSHBYTE, 3,	/* 3 */
	HB_P_ARRAYPUSH,
	HB_P_JUMPNEAR, 11,	/* 11 (abs: 00671) */
	HB_P_PUSHLOCALNEAR, 1,	/* codeblockvar1 */
	HB_P_DUPLICATE,
	HB_P_PUSHLOCALREF, 255, 255,	/* localvar1 */
	HB_P_PUSHBYTE, 3,	/* 3 */
	HB_P_ARRAYPOP,
	HB_P_ENDBLOCK,
	HB_P_PUSHLOCALNEAR, 7,	/* ODLG */
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_FALSE,
	HB_P_PUSHNIL,
	HB_P_SENDSHORT, 11,
	HB_P_PUSHLOCALREF, 3, 0,	/* AOGETS */
	HB_P_PUSHBYTE, 3,	/* 3 */
	HB_P_ARRAYPOP,
/* 00690 */ HB_P_LINEOFFSET, 26,	/* 459 */
	HB_P_MESSAGE, 40, 0,	/* REDEFINE */
	HB_P_PUSHSYMNEAR, 48,	/* TBUTTON */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_PUSHINT, 245, 1,	/* 501 */
	HB_P_PUSHBLOCK, 39, 0,	/* 39 */
	0, 0,	/* number of local parameters (0) */
	5, 0,	/* number of local variables (5) */
	5, 0,	/* LEXPORT */
	4, 0,	/* ATIPOSEXP */
	6, 0,	/* OLBX */
	2, 0,	/* ADADOS */
	7, 0,	/* ODLG */
	HB_P_TRUE,
	HB_P_POPLOCALNEAR, 255,	/* localvar1 */
	HB_P_PUSHSYMNEAR, 154,	/* ONEXPRELEASE */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 254,	/* localvar2 */
	HB_P_PUSHLOCALNEAR, 253,	/* localvar3 */
	HB_P_PUSHLOCALNEAR, 252,	/* localvar4 */
	HB_P_DOSHORT, 3,
	HB_P_MESSAGE, 59, 0,	/* END */
	HB_P_PUSHLOCALNEAR, 251,	/* localvar5 */
	HB_P_SENDSHORT, 0,
	HB_P_ENDBLOCK,
	HB_P_PUSHLOCALNEAR, 7,	/* ODLG */
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_FALSE,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_FALSE,
	HB_P_SENDSHORT, 10,
	HB_P_POP,
/* 00754 */ HB_P_LINEOFFSET, 27,	/* 460 */
	HB_P_MESSAGE, 40, 0,	/* REDEFINE */
	HB_P_PUSHSYMNEAR, 48,	/* TBUTTON */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_PUSHINT, 254, 1,	/* 510 */
	HB_P_PUSHBLOCK, 17, 0,	/* 17 */
	0, 0,	/* number of local parameters (0) */
	1, 0,	/* number of local variables (1) */
	7, 0,	/* ODLG */
	HB_P_MESSAGE, 59, 0,	/* END */
	HB_P_PUSHLOCALNEAR, 255,	/* localvar1 */
	HB_P_SENDSHORT, 0,
	HB_P_ENDBLOCK,
	HB_P_PUSHLOCALNEAR, 7,	/* ODLG */
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_FALSE,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_FALSE,
	HB_P_SENDSHORT, 10,
	HB_P_POP,
/* 00796 */ HB_P_LINEOFFSET, 29,	/* 462 */
	HB_P_MESSAGE, 74, 0,	/* ACTIVATE */
	HB_P_PUSHLOCALNEAR, 7,	/* ODLG */
	HB_P_MESSAGE, 75, 0,	/* BLCLICKED */
	HB_P_PUSHLOCALNEAR, 7,	/* ODLG */
	HB_P_SENDSHORT, 0,
	HB_P_MESSAGE, 76, 0,	/* BMOVED */
	HB_P_PUSHLOCALNEAR, 7,	/* ODLG */
	HB_P_SENDSHORT, 0,
	HB_P_MESSAGE, 77, 0,	/* BPAINTED */
	HB_P_PUSHLOCALNEAR, 7,	/* ODLG */
	HB_P_SENDSHORT, 0,
	HB_P_TRUE,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_MESSAGE, 79, 0,	/* BRCLICKED */
	HB_P_PUSHLOCALNEAR, 7,	/* ODLG */
	HB_P_SENDSHORT, 0,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_SENDSHORT, 10,
	HB_P_POP,
/* 00840 */ HB_P_LINEOFFSET, 31,	/* 464 */
	HB_P_PUSHLOCALNEAR, 5,	/* LEXPORT */
	HB_P_RETVALUE,
	HB_P_ENDPROC
/* 00846 */
   };

   hb_vmExecute( pcode, symbols );
}

HB_FUNC( ONEXPRELEASE )
{
   static const BYTE pcode[] =
   {
	HB_P_FRAME, 0, 3,	/* locals, params */
/* 00003 */ HB_P_BASELINE, 213, 1,	/* 469 */
	HB_P_PUSHLOCALNEAR, 1,	/* AEXPLIST */
	HB_P_MESSAGE, 150, 0,	/* NAT */
	HB_P_PUSHLOCALNEAR, 2,	/* OLBX */
	HB_P_SENDSHORT, 0,
	HB_P_ARRAYPUSH,
	HB_P_ONE,
	HB_P_ARRAYPUSH,
	HB_P_POPVARIABLE, 91, 0,	/* CEXPOBJ */
/* 00021 */ HB_P_LINEOFFSET, 1,	/* 470 */
	HB_P_PUSHLOCALNEAR, 3,	/* ADADOS */
	HB_P_ONE,
	HB_P_ARRAYPUSH,
	HB_P_POPVARIABLE, 92, 0,	/* CEXPFILE */
/* 00030 */ HB_P_LINEOFFSET, 2,	/* 471 */
	HB_P_PUSHLOCALNEAR, 3,	/* ADADOS */
	HB_P_PUSHBYTE, 2,	/* 2 */
	HB_P_ARRAYPUSH,
	HB_P_POPVARIABLE, 93, 0,	/* LEXPOPT */
/* 00040 */ HB_P_LINEOFFSET, 3,	/* 472 */
	HB_P_PUSHLOCALNEAR, 3,	/* ADADOS */
	HB_P_PUSHBYTE, 3,	/* 3 */
	HB_P_ARRAYPUSH,
	HB_P_POPVARIABLE, 94, 0,	/* LEXPOPEN */
/* 00050 */ HB_P_LINEOFFSET, 5,	/* 474 */
	HB_P_TRUE,
	HB_P_RETVALUE,
	HB_P_ENDPROC
/* 00055 */
   };

   hb_vmExecute( pcode, symbols );
}

HB_FUNC( CALLUSERFUNCTION )
{
   static const BYTE pcode[] =
   {
	HB_P_FRAME, 1, 2,	/* locals, params */
/* 00003 */ HB_P_BASELINE, 225, 1,	/* 481 */
	HB_P_PUSHLOCALNEAR, 1,	/* FNAME */
	HB_P_PUSHSTRSHORT, 9,	/* 9 */
	'X', 'B', 'A', 'S', 'E', 'S', 'T', 'R', 0, 
	HB_P_EXACTLYEQUAL,
	HB_P_JUMPFALSENEAR, 25,	/* 25 (abs: 00045) */
/* 00022 */ HB_P_LINEOFFSET, 1,	/* 482 */
	HB_P_PUSHSYMNEAR, 25,	/* STR */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 2,	/* FPARAMS */
	HB_P_ONE,
	HB_P_ARRAYPUSH,
	HB_P_PUSHLOCALNEAR, 2,	/* FPARAMS */
	HB_P_PUSHBYTE, 2,	/* 2 */
	HB_P_ARRAYPUSH,
	HB_P_PUSHLOCALNEAR, 2,	/* FPARAMS */
	HB_P_PUSHBYTE, 3,	/* 3 */
	HB_P_ARRAYPUSH,
	HB_P_FUNCTIONSHORT, 3,
	HB_P_POPLOCALNEAR, 3,	/* RES */
/* 00045 */ HB_P_LINEOFFSET, 4,	/* 485 */
	HB_P_PUSHLOCALNEAR, 3,	/* RES */
	HB_P_RETVALUE,
	HB_P_ENDPROC
/* 00051 */
   };

   hb_vmExecute( pcode, symbols );
}

HB_FUNC( ALLFILESEXIST )
{
   static const BYTE pcode[] =
   {
	HB_P_FRAME, 3, 1,	/* locals, params */
/* 00003 */ HB_P_BASELINE, 237, 1,	/* 493 */
	HB_P_TRUE,
	HB_P_POPLOCALNEAR, 2,	/* LEXIST */
	HB_P_LOCALNEARSETINT, 3, 0, 0,	/* I 0*/
	HB_P_PUSHSYMNEAR, 84,	/* LEN */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 1,	/* AFILES */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_POPLOCALNEAR, 4,	/* IMAX */
/* 00022 */ HB_P_LINEOFFSET, 2,	/* 495 */
	HB_P_FALSE,
	HB_P_PUSHLOCALNEARINC, 3,	/* I */
	HB_P_PUSHLOCALNEAR, 4,	/* IMAX */
	HB_P_LESSEQUAL,
	HB_P_JUMPFALSENEAR, 5,	/* 5 (abs: 00035) */
	HB_P_POP,
	HB_P_PUSHLOCALNEAR, 2,	/* LEXIST */
	HB_P_JUMPFALSENEAR, 18,	/* 18 (abs: 00053) */
/* 00037 */ HB_P_LINEOFFSET, 3,	/* 496 */
	HB_P_PUSHSYMNEAR, 155,	/* FILE */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 1,	/* AFILES */
	HB_P_PUSHLOCALNEAR, 3,	/* I */
	HB_P_ARRAYPUSH,
	HB_P_FUNCTIONSHORT, 1,
	HB_P_POPLOCALNEAR, 2,	/* LEXIST */
	HB_P_JUMPNEAR, 227,	/* -29 (abs: 00022) */
/* 00053 */ HB_P_LINEOFFSET, 6,	/* 499 */
	HB_P_PUSHLOCALNEAR, 2,	/* LEXIST */
	HB_P_RETVALUE,
	HB_P_ENDPROC
/* 00059 */
   };

   hb_vmExecute( pcode, symbols );
}

HB_FUNC( SHOWPROGRESS )
{
   static const BYTE pcode[] =
   {
	HB_P_FRAME, 1, 3,	/* locals, params */
/* 00003 */ HB_P_BASELINE, 251, 1,	/* 507 */
	HB_P_PUSHLOCALNEAR, 1,	/* X */
	HB_P_ZERO,
	HB_P_EXACTLYEQUAL,
	HB_P_JUMPFALSENEAR, 19,	/* 19 (abs: 00029) */
/* 00012 */ HB_P_LINEOFFSET, 1,	/* 508 */
	HB_P_LOCALNEARSETSTR, 4, 9, 0,	/* RES 9*/
	'P', 'r', 'e', 'p', 'a', 'r', 'e', ' ', 0, 
	HB_P_JUMPNEAR, 51,	/* 51 (abs: 00078) */
/* 00029 */ HB_P_LINEOFFSET, 2,	/* 509 */
	HB_P_PUSHLOCALNEAR, 1,	/* X */
	HB_P_ONE,
	HB_P_EXACTLYEQUAL,
	HB_P_JUMPFALSENEAR, 18,	/* 18 (abs: 00053) */
/* 00037 */ HB_P_LINEOFFSET, 3,	/* 510 */
	HB_P_LOCALNEARSETSTR, 4, 8, 0,	/* RES 8*/
	'E', 'x', 'p', 'o', 'r', 't', ' ', 0, 
	HB_P_JUMPNEAR, 27,	/* 27 (abs: 00078) */
/* 00053 */ HB_P_LINEOFFSET, 4,	/* 511 */
	HB_P_PUSHLOCALNEAR, 1,	/* X */
	HB_P_PUSHBYTE, 2,	/* 2 */
	HB_P_EXACTLYEQUAL,
	HB_P_JUMPFALSENEAR, 18,	/* 18 (abs: 00078) */
/* 00062 */ HB_P_LINEOFFSET, 5,	/* 512 */
	HB_P_LOCALNEARSETSTR, 4, 10, 0,	/* RES 10*/
	'P', 'r', 'i', 'n', 't', 'i', 'n', 'g', ' ', 0, 
/* 00078 */ HB_P_LINEOFFSET, 9,	/* 516 */
	HB_P_PUSHLOCALNEAR, 3,	/* Z */
	HB_P_ONE,
	HB_P_EXACTLYEQUAL,
	HB_P_JUMPFALSENEAR, 18,	/* 18 (abs: 00102) */
/* 00086 */ HB_P_LINEOFFSET, 10,	/* 517 */
	HB_P_PUSHSTRSHORT, 8,	/* 8 */
	'S', 't', 'a', 'r', 't', 'e', 'd', 0, 
	HB_P_LOCALNEARADD, 4,	/* RES */
	HB_P_JUMPNEAR, 77,	/* 77 (abs: 00177) */
/* 00102 */ HB_P_LINEOFFSET, 11,	/* 518 */
	HB_P_PUSHLOCALNEAR, 3,	/* Z */
	HB_P_PUSHBYTE, 2,	/* 2 */
	HB_P_EXACTLYEQUAL,
	HB_P_JUMPFALSENEAR, 38,	/* 38 (abs: 00147) */
/* 00111 */ HB_P_LINEOFFSET, 12,	/* 519 */
	HB_P_PUSHSTRSHORT, 9,	/* 9 */
	'F', 'i', 'n', 'i', 's', 'h', 'e', 'd', 0, 
	HB_P_LOCALNEARADD, 4,	/* RES */
/* 00126 */ HB_P_LINEOFFSET, 13,	/* 520 */
	HB_P_PUSHSTRSHORT, 1,	/* 1 */
	0, 
	HB_P_POPVARIABLE, 39, 0,	/* CSTAT2 */
/* 00134 */ HB_P_LINEOFFSET, 14,	/* 521 */
	HB_P_MESSAGE, 100, 0,	/* REFRESH */
	HB_P_PUSHVARIABLE, 65, 0,	/* OSTAT2 */
	HB_P_SENDSHORT, 0,
	HB_P_POP,
	HB_P_JUMPNEAR, 32,	/* 32 (abs: 00177) */
/* 00147 */ HB_P_LINEOFFSET, 15,	/* 522 */
	HB_P_PUSHLOCALNEAR, 3,	/* Z */
	HB_P_PUSHBYTE, 3,	/* 3 */
	HB_P_EXACTLYEQUAL,
	HB_P_JUMPFALSENEAR, 23,	/* 23 (abs: 00177) */
/* 00156 */ HB_P_LINEOFFSET, 16,	/* 523 */
	HB_P_PUSHLOCALNEAR, 4,	/* RES */
	HB_P_PUSHSTRSHORT, 4,	/* 4 */
	' ', '-', ' ', 0, 
	HB_P_PLUS,
	HB_P_PUSHSYMNEAR, 25,	/* STR */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 2,	/* Y */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_PLUS,
	HB_P_POPLOCALNEAR, 4,	/* RES */
/* 00177 */ HB_P_LINEOFFSET, 18,	/* 525 */
	HB_P_PUSHLOCALNEAR, 4,	/* RES */
	HB_P_POPVARIABLE, 38, 0,	/* CSTAT1 */
/* 00184 */ HB_P_LINEOFFSET, 19,	/* 526 */
	HB_P_MESSAGE, 100, 0,	/* REFRESH */
	HB_P_PUSHVARIABLE, 64, 0,	/* OSTAT1 */
	HB_P_SENDSHORT, 0,
	HB_P_POP,
/* 00195 */ HB_P_LINEOFFSET, 20,	/* 527 */
	HB_P_ENDPROC
/* 00198 */
   };

   hb_vmExecute( pcode, symbols );
}

HB_FUNC( SHOWPROCESS )
{
   static const BYTE pcode[] =
   {
	HB_P_FRAME, 1, 1,	/* locals, params */
/* 00003 */ HB_P_BASELINE, 22, 2,	/* 534 */
	HB_P_PUSHVARIABLE, 6, 0,	/* LSHOWCUSTNAME */
	HB_P_JUMPFALSENEAR, 43,	/* 43 (abs: 00052) */
/* 00011 */ HB_P_LINEOFFSET, 1,	/* 535 */
	HB_P_PUSHSTRSHORT, 15,	/* 15 */
	'P', 'r', 'o', 'c', 'c', 'e', 's', 's', 'i', 'n', 'g', ' ', '-', ' ', 0, 
	HB_P_PUSHSYMNEAR, 156,	/* TRIM */
	HB_P_PUSHNIL,
	HB_P_ONE,
	HB_P_PUSHALIASEDVAR, 22, 0,	/* COMPANY */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_PLUS,
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	' ', 0, 
	HB_P_PLUS,
	HB_P_PUSHLOCALNEAR, 1,	/* SOBJECTNAME */
	HB_P_PLUS,
	HB_P_POPLOCALNEAR, 2,	/* CRES */
	HB_P_JUMPNEAR, 27,	/* 27 (abs: 00077) */
/* 00052 */ HB_P_LINEOFFSET, 3,	/* 537 */
	HB_P_PUSHSTRSHORT, 16,	/* 16 */
	'P', 'r', 'o', 'c', 'c', 'e', 's', 's', 'i', 'n', 'g', ' ', '-', ' ', ' ', 0, 
	HB_P_PUSHLOCALNEAR, 1,	/* SOBJECTNAME */
	HB_P_PLUS,
	HB_P_POPLOCALNEAR, 2,	/* CRES */
/* 00077 */ HB_P_LINEOFFSET, 5,	/* 539 */
	HB_P_PUSHLOCALNEAR, 2,	/* CRES */
	HB_P_POPVARIABLE, 39, 0,	/* CSTAT2 */
/* 00084 */ HB_P_LINEOFFSET, 6,	/* 540 */
	HB_P_MESSAGE, 100, 0,	/* REFRESH */
	HB_P_PUSHVARIABLE, 65, 0,	/* OSTAT2 */
	HB_P_SENDSHORT, 0,
	HB_P_POP,
/* 00095 */ HB_P_LINEOFFSET, 7,	/* 541 */
	HB_P_ENDPROC
/* 00098 */
   };

   hb_vmExecute( pcode, symbols );
}

